config/routes.rb
R4a::Application.routes.draw do

  resources :app_nivels
  resources :reporte_de_problemas

  ActiveAdmin.routes(self)
  root :to => "home#index"
  devise_for :users, :controllers => {:registrations => "registrations"}
  resources :users
  resources :homereportes
  get '/new_employee'                    => 'homereportes#new_employee'

  get '/homereportes'                    => 'homereportes#index'
  get '/areas'                           => 'homereportes#new_area'
  get '/editar_area/:id_area'            => 'homereportes#editar_area'
  post '/create_area    '                => 'homereportes#create_area'
  post '/create_employee'                => 'homereportes#create_employee'
  get '/delete_employee'                 => 'homereportes#delete_employee'
  get '/new_task'                        => 'homereportes#new_task'
  get '/delete_task'                     => 'homereportes#delete_task'
  post '/create_task'                    => 'homereportes#create_task'
  get  '/create_taskuser'                => 'homereportes#create_taskuser'
  post '/create_areauser'                => 'homereportes#create_areauser'
  post '/create_areaempleado'            => 'homereportes#create_areaempleado'
  get  '/log_home_office'                => 'homereportes#log_home_office'
  get '/delete_areaempleado'             => 'homereportes#delete_areaempleado'
  get '/delete_areajefe'                 => 'homereportes#delete_areajefe'
  get '/delete_taskuser'                 => 'homereportes#delete_taskuser'
  get '/edit_taskuser'                   => 'homereportes#edit_taskuser'
  post '/update_taskuser'                => 'homereportes#update_taskuser'
  post '/checkjefes'                     => 'homereportes#checkjefes'
  get '/edit_task'                       => 'homereportes#edit_task'
  post '/update_task'                    => 'homereportes#update_task'

  post '/zammad_create'                  => 'home#zammad_create'
  get '/privacy'                         => 'home#privacy'
  get '/ayuda'                           => 'home#ayuda'
  get '/personalizar_menu'               => 'home#personalizar_menu'
  get '/personalizar_menu_t'             => 'home#personalizar_menu_t'


  get 'checadores/enviar_chequeos' => 'checadores#enviar_chequeos'
  #get 'checadores/index'

  get '/app_rol_nivel'                   => 'app_rol_nivel#index'
  get '/app_rol_nivel_acceso'            => 'app_rol_nivel#app_rol_nivel_acceso'

  get 'ant_saldos'                       => 'ant_saldos#ant_saldos'
  get 'ant_saldos_clientes'              => 'ant_saldos#ant_saldos_clientes'
  get 'ant_saldos_clientes_nombre_rfc'   => 'ant_saldos#ant_saldos_clientes_nombre_rfc'
  get 'ant_saldos_cliente'               => 'ant_saldos#ant_saldos_cliente'
  get 'ant_saldos_cliente_datos'         => 'ant_saldos#ant_saldos_cliente_datos'
  post 'ant_saldos_cliente_editar'       => 'ant_saldos#ant_saldos_cliente_editar'
  get 'ant_saldos_cliente_anyo'          => 'ant_saldos#ant_saldos_cliente_anyo'
  get 'ant_saldos_cliente_hist1'         => 'ant_saldos#ant_saldos_cliente_hist1'
  get 'ant_saldos_sucursal'              => 'ant_saldos#ant_saldos_sucursal'
  get 'ant_saldos_detalle'               => 'ant_saldos#ant_saldos_detalle'
  get 'ant_saldos_vencidas'              => 'ant_saldos#ant_saldos_vencidas'
  get 'ant_saldos_comentarios'           => 'ant_saldos#ant_saldos_comentarios'
  get 'ant_saldos_mails'                 => 'ant_saldos#ant_saldos_mails'
  get 'ant_saldos_mails_new'             => 'ant_saldos#ant_saldos_mails_new'
  post 'ant_saldos_mails'                => 'ant_saldos#ant_saldos_mails_create'
  delete 'ant_saldos_mails'              => 'ant_saldos#ant_saldos_mails_delete'
  get 'enviar_mails_de_aclaracion_robot' => 'ant_saldos#enviar_mails_de_aclaracion_robot'
  get 'enviar_mails_de_aclaracion_robot_index' => 'ant_saldos#enviar_mails_de_aclaracion_robot_index'
  get 'ant_saldos_sucursal'              => 'ant_saldos#ant_saldos_sucursal'

  get 'replicasuc'                       => 'replicasuc#replicasuc'

  get 'calc_objetivos'                              => 'calc_objetivos#calc_objetivos'
  get 'calc_objetivos_objetivo'                     => 'calc_objetivos#calc_objetivos_objetivo'
  get 'calc_objetivos_estadistica'                  => 'calc_objetivos#calc_objetivos_estadistica'
  get 'calc_objetivos_analisis'                     => 'calc_objetivos#calc_objetivos_analisis'
  get 'calc_objetivos_ajax_subagrupa'               => 'calc_objetivos#ajax_subagrupa'
  get 'calc_objetivos_ajax_agrupasuc'               => 'calc_objetivos#ajax_agrupasuc'
  get 'calc_objetivos_gridcrecireal_porce_update'   => 'calc_objetivos#calc_objetivos_gridcrecireal_porce_update'
  get 'calc_objetivos_gridcrecireal_obj_update'     => 'calc_objetivos#calc_objetivos_gridcrecireal_obj_update'

  get 'repobjetivos'                     => 'repobjetivos#repobjetivos_zona'
  get 'repobjetivos_zona'                => 'repobjetivos#repobjetivos_zona'
  get 'repobjetivos_suc'                 => 'repobjetivos#repobjetivos_suc'
  get 'repobjetivos_det_suc'             => 'repobjetivos#repobjetivos_det_suc'

  get 'signos_vitales'                   => 'signos_vitales#signos_vitales_zona'
  get 'signos_vitales_zona'              => 'signos_vitales#signos_vitales_zona'
  get 'signos_vitales_suc'               => 'signos_vitales#signos_vitales_suc'
  get 'signos_vitales_graf'              => 'signos_vitales#signos_vitales_graf'

  get 'estaventas'                       => 'estaventas#estaventas'
  get 'estaventas_ajax_subagrupa'        => 'estaventas#ajax_subagrupa'
  get 'estaventas_ajax_agrupasuc'        => 'estaventas#ajax_agrupasuc'

  get 'comprobantes_nomina'                   => 'comprobantes_nomina#index'
  get 'comprobantes_nomina_descarga/:nomcomp' => 'comprobantes_nomina#comprobantes_nomina_descarga'
  get 'comprobantes_nomina_ayuda'             => 'comprobantes_nomina#ayuda'
  get 'contrato_colectivo'                    => 'comprobantes_nomina#contrato_colectivo'

  get 'claves_pdv' => 'claves_pdv#index'

  get 'bajas'         => 'bajas#index'
  get 'bajas_obra'    => 'bajas#bajas_obra'
  get 'bajas_detalle' => 'bajas#bajas_detalle'
  get 'bajas_mails'       => 'bajas#bajas_mails'
  get 'bajas_mails_new'   => 'bajas#bajas_mails_new'
  post 'bajas_mails'      => 'bajas#bajas_mails_create'
  delete 'bajas_mails'    => 'bajas#bajas_mails_delete'
  get 'bajas_enviar_mails_robot' => 'bajas#bajas_enviar_mails_robot'
  get 'bajas_enviar_mails_robot_index' => 'bajas#bajas_enviar_mails_robot_index'
  get 'bajas/export_excel' => 'bajas#export_excel'

  get 'consultas'                => 'consultas#index'
  get 'consultas_reportes'       => 'consultas#reportes'

  get 'reportes_bi'              => 'reportes_bi#index'
  get 'reportes_bi_reportes'     => 'reportes_bi#reportes'

  get 'contenedores'             => 'contenedores#index'
  get 'contenedores_contenedor'  => 'contenedores#contenedor'
  get 'contenedores_mails'       => 'contenedores#contenedores_mails'
  get 'contenedores_mails_new'   => 'contenedores#contenedores_mails_new'
  post 'contenedores_mails'      => 'contenedores#contenedores_mails_create'
  delete 'contenedores_mails'    => 'contenedores#contenedores_mails_delete'
  get 'contenedores_enviar_mails_robot' => 'contenedores#contenedores_enviar_mails_robot'
  get 'contenedores_enviar_mails_robot_index' => 'contenedores#contenedores_enviar_mails_robot_index'

  get  'conciliaciones'          => 'conciliaciones#index'
  get  'conciliacion'            => 'conciliaciones#show'
  get  'conciliaciones_robot'    => 'conciliaciones#robot'

  get 'obras'                    => 'obras#obras'
  get 'obra'                     => 'obras#obra'
  get 'obra_detalle'             => 'obras#obra_detalle'
  post 'obra_new_comment'        => 'obras#obra_new_comment'
  post 'obra_edit_status'        => 'obras#obra_edit_status'
  post 'obra_porc_desc_script'   => 'obras#obra_porc_desc_script'

  get 'bloqueo_tarjetas_club_comex' => 'bloqueo_tarjetas_club_comex#index'
  get 'bloqueo_tarjetas_club_comex_new' => 'bloqueo_tarjetas_club_comex#new'
  post 'bloqueo_tarjetas_club_comex_create' => 'bloqueo_tarjetas_club_comex#create'
  get 'bloqueo_tarjetas_club_comex_detalle' => 'bloqueo_tarjetas_club_comex#show'
  post 'bloqueo_tarjetas_club_comex_update' => 'bloqueo_tarjetas_club_comex#update'

  get  'todos'                   => 'todos#todos'
  get  'todos_new'               => 'todos#todos_new'
  post 'todos_create'            => 'todos#todos_create'
  post 'todos_update'            => 'todos#todos_update'
  post 'todos_respuesta_create'  => 'todos#todos_respuesta_create'
  get  'todos_show'              => 'todos#todos_show'
  get  'todos_involucrados_edit' => 'todos#todos_involucrados_edit'
  post 'todos_involucrados_edit_post' => 'todos#todos_involucrados_edit_post'
  resources :todos_respuestas_files

  get  'tickets'                   => 'tickets#tickets'
  get  'tickets_new'               => 'tickets#tickets_new'
  post 'tickets_create'            => 'tickets#tickets_create'
  post 'tickets_update'            => 'tickets#tickets_update'
  post 'tickets_respuesta_create'  => 'tickets#tickets_respuesta_create'
  get  'tickets_show'              => 'tickets#tickets_show'
  get  'tickets_involucrados_edit' => 'tickets#tickets_involucrados_edit'
  post 'tickets_involucrados_edit_post' => 'tickets#tickets_involucrados_edit_post'
  get  'tickets_assign_myself'     => 'tickets#tickets_update'
  get  'tickets_programados'       => 'tickets#tickets_programados'
  get  'tickets_programados_new'   => 'tickets#tickets_programados_new'
  post 'tickets_programados_create'=> 'tickets#tickets_programados_create'
  get  'tickets_programados_edit'  => 'tickets#tickets_programados_edit'
  post 'tickets_programados_update'=> 'tickets#tickets_programados_update'
  delete 'tickets_programados_destroy' => 'tickets#tickets_programados_destroy'
  get  'tickets_programados_robot' => 'tickets#tickets_programados_robot'

app/views/signos_vitales/signos_vitales_suc.html.erb
<h3 class="text-center">Signos Vitales</h3>
<div class="col-md-12 col-sm-12 center-block inner-top-sm">
  <% if @continua > 0 %>

    <h5><%= @descriptipoclientes %></h5>
    <h5><%= @nommes + " de " + params[:periodo].to_s.first(4) %></h5>
    <h5>Zona: <%= @zona + "-" + @nomzona[0]['NomZona'] %></h5>
    <% if @signosvitalessuc.count > 0 %>

      <table cellpadding="0" cellspacing="0" border="0" class="table table-hover table-bordered table-striped text-center" id="example">

        <thead>
          <tr>
            <th><a href="#" data-toggle="tooltip" title="Numero de Sucursal">Sucursal</a></th>
            <th><a href="#" data-toggle="tooltip" title="Nombre de Sucursal">Nombre</a></th>
            <th><a href="#" data-toggle="tooltip" title="Tickets/Dia">Tickets/Dia</a></th>
            <th><a href="#" data-toggle="tooltip" title="Ticket Promedio">Ticket Promedio</a></th>
            <th><a href="#" data-toggle="tooltip" title="Artículos/Ticket">Articulos/Ticket</a></th>
            <th><a href="#" data-toggle="tooltip" title="Renglones/Ticket">Renglones/Ticket</a></th>
          </tr>
        </thead>

        <tbody>
          <% @signosvitalessuc.each do |m| %>
            <tr>
              <td><%= m['ColSucursal'] %></td>
              <td><%= m['ColNombre'] %></td>
              <td><%= link_to number_with_delimiter(m['ColTicketsDia'], :locale => :mx, :precision => 2), "/signos_vitales_graf?zona=#{@zona}&suc=#{m['ColSucursal']}&tipoclientes=#{@tipoclientes}&signovit=1&sin_navegador=1", :target => "_blank", :style=>'color:#FF6666', :class => "css_class" %></td>
              <td><%= link_to number_to_currency(m['ColTicketPromedio'], :locale => :mx, :precision => 2), "/signos_vitales_graf?zona=#{@zona}&suc=#{m['ColSucursal']}&tipoclientes=#{@tipoclientes}&signovit=2&sin_navegador=1", :target => "_blank", :style=>'color:#009933', :class => "css_class" %></td>
              <td><%= link_to number_with_delimiter(m['ColArticulosTicket'], :locale => :mx, :precision => 2), "/signos_vitales_graf?zona=#{@zona}&suc=#{m['ColSucursal']}&tipoclientes=#{@tipoclientes}&signovit=3&sin_navegador=1", :target => "_blank", :style=>'color:#999900', :class => "css_class" %></td>
              <td><%= link_to number_with_delimiter(m['ColRenglonesTicket'], :locale => :mx, :precision => 2), "/signos_vitales_graf?zona=#{@zona}&suc=#{m['ColSucursal']}&tipoclientes=#{@tipoclientes}&signovit=4&sin_navegador=1", :target => "_blank", :style=>'color:#9966FF', :class => "css_class" %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
      <br>
      <%= link_to "Descargar para Excel", signos_vitales_suc_path(zona: @zona, periodo: @anomes, tipoclientes: @tipoclientes, format: "csv") %>

    <% else %>
      <br>
      Sin Datos.
    <% end %>
  <% end %>
</div>


<% if @zona.to_i>0 && @suc.to_i>0 %>
  <div class="loader-form">
    <form class="form" role="form">
      <div class="form-group">

        <% numanoact = DateTime.now.year %>
        <% nummesact = DateTime.now.month %>
        <% nommesact = '' %>
        <br>
        <br>
        <br>
        <br>
        <div class="panel panel-primary">
          <div class="panel-heading">Seleccione</div>
          <div class="panel-body">

            <div class="control-group">
              <label class="control-label col-md-2" for="inputPassword">Periodo:</label>
              <div class="controls">
                <select class="combobox" name="periodo" id="idperiodo">
                  <% 60.times do |i| %>
                    <% nommesact = case nummesact %>
                      <% when  1 then 'Enero' %>
                      <% when  2 then 'Febrero' %>
                      <% when  3 then 'Marzo' %>
                      <% when  4 then 'Abril' %>
                      <% when  5 then 'Mayo' %>
                      <% when  6 then 'Junio' %>
                      <% when  7 then 'Julio' %>
                      <% when  8 then 'Agosto' %>
                      <% when  9 then 'Septiembre' %>
                      <% when 10 then 'Octubre' %>
                      <% when 11 then 'Noviembre' %>
                      <% when 12 then 'Diciembre' %>
                    <% end %>
                    <option value="<%= numanoact*100 + nummesact %>"><%= nommesact + ' ' + numanoact.to_s %></option>
                    <% nummesact = nummesact -1 %>
                    <% if nummesact == 0 %>
                      <% nummesact = 12 %>
                      <% numanoact = numanoact -1 %>
                    <% end %>
                  <% end %>
                </select>
                <script>
                  $('#idperiodo').val( <%= params[:periodo].to_s %> )
                </script>
              </div>
            </div>

            <br>
            <div class="control-group">
              <label class="control-label col-md-2" for="inputPassword">Tipo de Clientes:</label>
              <div class="controls">
                <select class="combobox" name="tipoclientes" id="idtipoclientes">
                  <option value="0">Todos</option>
                  <option value="1">Público en general</option>
                  <option value="2">Clientes conocidos</option>
                </select>
                <script>
                  $('#idtipoclientes').val( <%= params[:tipoclientes].to_s %> )
                </script>
              </div>
            </div>

          </div>
        </div>

      </div>
      <div class="form-actions">
        <button class="btn btn-primary go-to-filter">Consultar</button>
      </div>
    </form>
  </div>
<% end %>


<script src="/js/jquery.dataTables.min.js"></script>
<script src="/js/dataTables.bootstrap4.min.js"></script>


<style type="text/css">
label{
  display: none;
}
.dataTables_filter.md-form {
    margin-top: .55rem;
}
.dataTables_filter.md-form input{
    font-weight: 300;
}
.dataTables_wrapper .row {
    margin-bottom: 1.5rem;
}
div.dataTables_wrapper div.dataTables_info {
    padding-top: 0;
    padding-bottom: 1rem;
}
.dataTables_paginate {
    float: right;
}
.dataTables_filter {
    float: right;
}
</style>

<script type="text/javascript">
$(document).ready(function() {
  $('#example').DataTable({"pageLength": 100 });
  $('.dataTables_wrapper').find('label').each(function() {
    $(this).parent().append($(this).children());
  });
  $('.dataTables_filter').find('input').each(function() {
    $('input').attr("placeholder", "Buscar");
    $('input').removeClass('form-control-sm');
  });
  $('.dataTables_length').addClass('d-flex flex-row');
  $('.dataTables_filter').addClass('md-form');
  $('select').addClass('mdb-select');
  $('.mdb-select').removeClass('form-control form-control-sm');
  $('.dataTables_filter').find('label').remove();
});
</script>

app/views/signos_vitales/signos_vitales_zona.html.erb
<h3 class="text-center">Signos Vitales por Zona</h3>
<div class="col-md-12 col-sm-12 center-block inner-top-sm">
  <% if @continua > 0 %>

    <h5 class="text-right"><%= @descriptipoclientes %></h5>
    <h5 class="text-right"><%= @nommes + " de " + params[:periodo].to_s.first(4) %></h5>
    <% if @signosvitaleszona.count > 0 %>

      <table cellpadding="0" cellspacing="0" border="0" class="table table-hover table-bordered table-striped text-center" id="example">

        <thead>
          <tr>
          <th><a href="#" data-toggle="tooltip" title="Numero de Zona">Zona</a></th>
          <th><a href="#" data-toggle="tooltip" title="Nombre de Zona">Nombre</a></th>
          <th><a href="#" data-toggle="tooltip" title="Tickets/Dia">Tickets/Dia</a></th>
          <th><a href="#" data-toggle="tooltip" title="Ticket Promedio">Ticket Promedio</a></th>
          <th><a href="#" data-toggle="tooltip" title="Artículos/Ticket">Articulos/Ticket</a></th>
          <th><a href="#" data-toggle="tooltip" title="Renglones/Ticket">Renglones/Ticket</a></th>
          </tr>
        </thead>

        <tbody class="buscar">
          <% @signosvitaleszona.each do |m|  %>
            <tr>
              <td><%= m['ColZona'] %></td>
              <td><%= link_to m['ColNombre'], "/signos_vitales_suc?zona=#{m['ColZona']}&periodo=#{@anomes}&tipoclientes=#{@tipoclientes}" %></td>
              <td><%= link_to number_with_delimiter(m['ColTicketsDia'], :locale => :mx, :precision => 2), "/signos_vitales_graf?zona=#{m['ColZona']}&tipoclientes=#{@tipoclientes}&signovit=1&sin_navegador=1", :target => "_blank", :style=>'color:#FF6666', :class => "css_class" %></td>
              <td><%= link_to number_to_currency(m['ColTicketPromedio'], :locale => :mx, :precision => 2), "/signos_vitales_graf?zona=#{m['ColZona']}&tipoclientes=#{@tipoclientes}&signovit=2&sin_navegador=1", :target => "_blank", :style=>'color:#009933', :class => "css_class" %></td>
              <td><%= link_to number_with_delimiter(m['ColArticulosTicket'], :locale => :mx, :precision => 2), "/signos_vitales_graf?zona=#{m['ColZona']}&tipoclientes=#{@tipoclientes}&signovit=3&sin_navegador=1", :target => "_blank", :style=>'color:#999900', :class => "css_class" %></td>
              <td><%= link_to number_with_delimiter(m['ColRenglonesTicket'], :locale => :mx, :precision => 2), "/signos_vitales_graf?zona=#{m['ColZona']}&tipoclientes=#{@tipoclientes}&signovit=4&sin_navegador=1", :target => "_blank", :style=>'color:#9966FF', :class => "css_class" %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
      <br>
      <%= link_to "Descargar para Excel", signos_vitales_zona_path(periodo: @anomes, tipoclientes: @tipoclientes, format: "csv") %>


      <script type="text/javascript" language="javascript" src="/jquery.dataTables.min.js"></script>
      <script type="text/javascript" language="javascript" src="/dataTables.bootstrap.js"></script>
      <%= javascript_include_tag "/dt_v3" %>

    <% else %>
      <br>
      Sin Datos.
    <% end %>
  <% end %>
</div>


<div class="loader-form">
  <form class="form" role="form">
    <div class="form-group">

      <% numanoact = DateTime.now.year %>
      <% nummesact = DateTime.now.month %>
      <% nommesact = '' %>
      <br>
      <br>
      <br>
      <br>
      <div class="panel panel-primary">
        <div class="panel-heading text-center">Seleccione</div>
        <div class="panel-body">

          <div class="control-group col-md-12">
            <label class="control-label col-md-2" for="inputPassword">Periodo:</label>
            <div class="controls">
              <select class="custom-select col-md-6" name="periodo" id="idperiodo">
                <% 60.times do |i| %>
                  <% nommesact = case nummesact %>
                    <% when  1 then 'Enero' %>
                    <% when  2 then 'Febrero' %>
                    <% when  3 then 'Marzo' %>
                    <% when  4 then 'Abril' %>
                    <% when  5 then 'Mayo' %>
                    <% when  6 then 'Junio' %>
                    <% when  7 then 'Julio' %>
                    <% when  8 then 'Agosto' %>
                    <% when  9 then 'Septiembre' %>
                    <% when 10 then 'Octubre' %>
                    <% when 11 then 'Noviembre' %>
                    <% when 12 then 'Diciembre' %>
                  <% end %>
                  <option value="<%= numanoact*100 + nummesact %>"><%= nommesact + ' ' + numanoact.to_s %></option>
                  <% nummesact = nummesact -1 %>
                  <% if nummesact == 0 %>
                    <% nummesact = 12 %>
                    <% numanoact = numanoact -1 %>
                  <% end %>
                <% end %>
              </select>
              <script>
                $('#idperiodo').val( <%= params[:periodo].to_s %> )
              </script>
            </div>
          </div>

          <br>
          <div class="control-group col-md-12">
            <label class="control-label col-md-2" for="inputPassword">Tipo de Clientes:</label>
            <div class="controls">
              <select class="custom-select col-md-6" name="tipoclientes" id="idtipoclientes">
                <option value="0">Todos</option>
                <option value="1">Público en general</option>
                <option value="2">Clientes conocidos</option>
              </select>
              <script>
                $('#idtipoclientes').val( <%= params[:tipoclientes].to_s %> )
              </script>
            </div>
          </div>

        </div>
      </div>

    </div>
    <div class="form-actions text-center">
      <button class="btn btn-primary go-to-filter">Consultar</button>
    </div>
  </form>
</div>


<script src="/js/jquery.dataTables.min.js"></script>
<script src="/js/dataTables.bootstrap4.min.js"></script>


<style type="text/css">
label{
  display: none;
}
.dataTables_filter.md-form {
    margin-top: .55rem;
}
.dataTables_filter.md-form input{
    font-weight: 300;
}
.dataTables_wrapper .row {
    margin-bottom: 1.5rem;
}
div.dataTables_wrapper div.dataTables_info {
    padding-top: 0;
    padding-bottom: 1rem;
}
.dataTables_paginate {
    float: right;
}
.dataTables_filter {
    float: right;
}
</style>

<script type="text/javascript">
$(document).ready(function() {
  $('#example').DataTable({"pageLength": 100,  "bDestroy": true });
  $('.dataTables_wrapper').find('label').each(function() {
    $(this).parent().append($(this).children());
  });
  $('.dataTables_filter').find('input').each(function() {
    $('input').attr("placeholder", "Buscar");
    $('input').removeClass('form-control-sm');
  });
  $('.dataTables_length').addClass('d-flex flex-row');
  $('.dataTables_filter').addClass('md-form');
  $('select').addClass('mdb-select');
  $('.mdb-select').removeClass('form-control form-control-sm');
  $('.dataTables_filter').find('label').remove();
});
</script>