config/routes.rb
  get  'tickets_programados_edit'  => 'tickets#tickets_programados_edit'
  post 'tickets_programados_update'=> 'tickets#tickets_programados_update'
  delete 'tickets_programados_destroy' => 'tickets#tickets_programados_destroy'
  get  'tickets_programados_robot' => 'tickets#tickets_programados_robot'
  resources :tickets_respuestas_files, only: [:create]

  get  'revisiones'                => 'revisiones#revisiones'
  get  'revisiones_new'            => 'revisiones#revisiones_new'
  post 'revisiones_create_preview' => 'revisiones#revisiones_create_preview'
  post 'revisiones_create'         => 'revisiones#revisiones_create'
  get  'revisiones_show'           => 'revisiones#revisiones_show'

  get  'grupos'                   => 'grupos#grupos'
  get  'grupos_new'               => 'grupos#grupos_new'
  post 'grupos_create'            => 'grupos#grupos_create'
  get  'grupos_edit'              => 'grupos#grupos_edit'
  post 'grupos_update'            => 'grupos#grupos_update'
  delete 'grupos_destroy'         => 'grupos#grupos_destroy'
  get  'grupos_update_rol'        => 'grupos#grupos_update_rol'

  namespace :supervisiones do
    root :to                        => 'supervisiones#root'

    get  'programadas'              => 'supervisiones#programadas'
    get  'terminadas'               => 'supervisiones#terminadas'
    get  'supervision_terminada'    => 'supervisiones#supervision_terminada'
    get  'crear_supervision'        => 'supervisiones#crear_supervision'
    get  'realizar_supervision'     => 'supervisiones#crear_supervision'
    get  'nueva_supervision'        => 'supervisiones#nueva_supervision'
    post 'nueva_supervision'        => 'supervisiones#nueva_supervision_create'
    get  'supervision_en_curso'     => 'supervisiones#supervision_en_curso'
    post 'supervision_en_curso'     => 'supervisiones#supervision_en_curso_update'
    get  'supervision_en_curso_aci' => 'supervisiones#supervision_en_curso_aci'
    post 'supervision_en_curso_aci' => 'supervisiones#supervision_en_curso_aci_create'
    get  'supervisiones_en_curso'   => 'supervisiones#supervisiones_en_curso'
    get  'supervision_por_aprobar'  => 'supervisiones#supervision_por_aprobar'
    post 'supervision_por_aprobar'  => 'supervisiones#supervision_por_aprobar_update'
    get  'supervisiones_por_aprobar'=> 'supervisiones#supervisiones_por_aprobar'
    get  'supervisiones_por_programar' => 'supervisiones#supervisiones_por_programar'
    get  'programar_supervisiones'  => 'supervisiones#programar_supervisiones'
    post 'programar_supervisiones'  => 'supervisiones#programar_supervisiones_create'
    delete 'programar_supervisiones'=> 'supervisiones#programar_supervisiones_destroy'

    get  'checklists'               => 'checklists#index'
    get  'checklist_new'            => 'checklists#new'
    post 'checklist_create'         => 'checklists#create'
    get  'checklist_edit'           => 'checklists#edit'
    post 'checklist_update'         => 'checklists#update'
    delete 'checklist_destroy'      => 'checklists#destroy'

    get  'categories'               => 'categories#index'
    get  'category_new'             => 'categories#new'
    post 'category_create'          => 'categories#create'
    get  'category_edit'            => 'categories#edit'
    post 'category_update'          => 'categories#update'
    delete 'category_destroy'       => 'categories#destroy'

    get  'campos'                   => 'campos#index'
    get  'campo_new'                => 'campos#new'
    post 'campo_create'             => 'campos#create'
    get  'campo_edit'               => 'campos#edit'
    post 'campo_update'             => 'campos#update'
    delete 'campo_destroy'          => 'campos#destroy'

    get  'load_sucs'                => 'supervisiones#load_sucs'
    get  'load_cats'                => 'supervisiones#load_cats'

    get  'sup_test'                 => 'supervisiones#sup_test'

  end
  resources :sup_imagens

  namespace :notificaciones do
    get 'autorizaciones'            => 'autorizaciones#index'
    get 'autorizaciones/:id'        => 'autorizaciones#show'
    get 'auth_logs'                 => 'auth_logs#index'
    get 'auth_logs/:id'             => 'auth_logs#show'

    get 'notificaciones'            => 'notificaciones#index'

    get 'mails'                     => 'mails#mails'
    get 'mails_new'                 => 'mails#mails_new'
    get 'mails_edit'                => 'mails#mails_edit'
    post 'mails'                    => 'mails#mails_create'
    delete 'mails'                  => 'mails#mails_delete'

    get  'push_tokens'              => 'push_tokens#index'
    get  'push_token_test'          => 'push_tokens#push_token_test'

    resources :webhooks
  end

  get 'medidores' => 'tableros/layouts#index'
  get 'medidores_prueba' => 'tableros/medidores#prueba'
  namespace :tableros do
    root :to                        => 'layouts#index'

    resources :layouts
    resources :medidores
    get 'medidores_display_medidor' => 'medidores#medidores_display_medidor'
    resources :usuarios
  end

  namespace :auths do
    root :to                        => 'solicitudes#index'

    resources :solicitudes
    get 'solicitudes_update'  => 'solicitudes#update'
    post 'solicitudes_respuesta_create'  => 'solicitudes#respuesta_create'
    resources :flujos, except: [:edit, :update]
    resources :tipo_solicitudes
  end
  resources :auths_respuestas_files, only: [:create]

  namespace :ecommerce do
    root :to                        => 'pedidos#index'

    resources :pedidos, only: [:index, :show]
    post 'asignar_sucursal'  => 'pedidos#asignar_sucursal'
    post 'cambiar_status'  => 'pedidos#cambiar_status'

    resources :webservices, only: [:index, :show]
  end

  get 'webservices'                 => 'webservices#index'
  get 'webservices/pdv'             => 'webservices#pdv'
  post 'webservices/pdv/autoriza'   => 'webservices#pdv_autoriza'
  post 'webservices/ecommerce/pedido' => 'webservices#ecommerce_pedido'

  get  'documentos'                   => 'documentos#index'
  get  'documentos_admin'             => 'documentos#documentos_admin'
  get  'documentos_admin_new'         => 'documentos#documentos_admin_new'
  post 'documentos_admin_create'      => 'documentos#documentos_admin_create'
  get  'documentos_admin_edit'        => 'documentos#documentos_admin_edit'
  post 'documentos_admin_update'      => 'documentos#documentos_admin_update'
  delete 'documentos_admin_destroy'   => 'documentos#documentos_admin_destroy'
  get  'documentos_admin_image'       => 'documentos#documentos_admin_image'
  get  'documentos_admin_file'        => 'documentos#documentos_admin_file'
  get  'documentos_admin_multiple_files' => 'documentos#documentos_admin_multiple_files'

  resources :documentos_images
  resources :documentos_files

  get  'stock_sucursales'              => 'stock_sucursales#stock_sucursales'
  get  'stock_sucursales_existencias'  => 'stock_sucursales#stock_sucursales_existencias'

  get  'pdv'                    => 'pdv#pdv'
#  get  'pdv_devolver'           => 'pdv#pdv_devolver'
  get  'pdv_selvend'            => 'pdv#pdv_selvend'
  get  'pdv_selcli'             => 'pdv#pdv_selcli'
  get  'pdv_selsuc'             => 'pdv#pdv_selsuc'
  get  'pdv_selobra'            => 'pdv#pdv_selobra'
  get  'pdv_selprod'            => 'pdv#pdv_selprod'
  get  'pdv_selprod_edit'       => 'pdv#pdv_selprod_edit'
  post 'pdv_selprod_update'     => 'pdv#pdv_selprod_update'
  get  'pdv_selprod_destroy'    => 'pdv#pdv_selprod_destroy'
  get  'pdv_desc_global_edit'   => 'pdv#pdv_desc_global_edit'
  post 'pdv_desc_global_update' => 'pdv#pdv_desc_global_update'
  get  'pdv_cotiza_edit'        => 'pdv#pdv_cotiza_edit'
  post 'pdv_cotiza_update'      => 'pdv#pdv_cotiza_update'
  get  'pdv_pendientes'         => 'pdv#pdv_pendientes'
  get  'pdv_cotiza_terminada'   => 'pdv#pdv_cotiza_terminada'

  get  'estadisticas_ventas'   => 'estadisticas_ventas#index'
  get  'estadisticas_ventas/superior/:id'   => 'estadisticas_ventas#superior'
  get  'estadisticas_ventas/superior/intermedio/:id'   => 'estadisticas_ventas#intermedio'
  get  'estadisticas_ventas/superior/intermedio/sucursal/:id'   => 'estadisticas_ventas#sucursal'
  #post  'vendedor/:id'   => 'estadisticas_ventas#show'
  get 'estadisticas_ventas/superior/intermedio/sucursal/:id/vendedor/:id' => 'estadisticas_ventas#show_vendedor'
  post '/search_empleado/:id' => 'comisiones#search_empleado'


  get 'comisiones' => 'comisiones#index'
  get 'comisiones/:mes/:sucursal/:tipo' => 'comisiones#show_report'

  get 'comisiones_v1' => 'comisiones_v1#index'
  get 'comisiones_v1/:mes/:sucursal/:tipo' => 'comisiones_v1#show_report'
  get 'print_pdf/:id' => 'comisiones_v1#print_pdf'

  get 'reporte_sucursales/:id/:type' => 'reporte_sucursales#show'
  get 'estadisticas_ventas/export_excel' => 'estadisticas_ventas#export_excel'


  get 'reportes_vendedores' => 'reportes_vendedores#index'
  get 'reportes_vendedores/:id' => 'reportes_vendedores#show'
  get 'print_pdf_vend/:id/:month' => 'reportes_vendedores#print_pdf_vend'
  get 'exportar_excel/:month' => 'reportes_vendedores#exportar_excel'
  # get 'tickets/:id/:state' => 'tickets#change_settings'
  # get 'tickets/dashboard_tickets' => 'tickets#dashboard_tickets'
  # resources :tickets, only: [:index, :show, :create]
  # resources :ticket_groups
  resources :reporte_sucursales

  get 'detalle/sucursal/:id/vendedor/:id' =>'estadisticas_ventas#ver_detalle'

  ########################################################################
  # API
  ########################################################################
  namespace :api do
    namespace :v1 do
      get 'alive' => 'welcome#alive'
      get 'auth_alive' => 'welcome#auth_alive'
      resources :sessions, only: [:create, :destroy]
      post 'push_token', to: 'sessions#push_token'
      get 'notificaciones' => 'notificaciones#index'
      resources :calificaciones_reportes

app/controllers/auths/flujos_controller.rb
class Auths::FlujosController < ApplicationController
  before_filter :authenticate_user!
  before_filter :admin_only
  before_filter :find_flujo, only: [:show, :destroy]
  before_filter :obtiene_catalogos

  def index
    sql = "SELECT AuthsFlujos.*, '' as NombreUsuario FROM AuthsFlujos ORDER BY IdTipoSolicitud, NivelActual, IdUsuario"
    @flujos = @dbEsta.connection.select_all(sql)
    @flujos.each do |a|
      if a['IdUsuario'].to_i > 0
        u = User.where("id = #{User.sanitize(a['IdUsuario'])}").first
        a['NombreUsuario'] = u.name rescue ''
      end
    end
  end

  def new
    @new = true
    @flujo = {}
    @flujo['IdTipoSolicitud'] = 1
    @flujo['NivelActual'] = 0
    @flujo['IdUsuario'] = 2
    @flujo['DebeAutorizar'] = 0
    @flujo['NivelFuturo'] = 80
  end

  def create
    create_or_update
  end

  def show
  end

  def destroy
    sql = "DELETE FROM AuthsFlujos WHERE IdTipoSolicitud = #{User.sanitize(@id.first)} AND NivelActual = #{User.sanitize(@id[1])} AND IdUsuario = #{User.sanitize(@id.last)}"
    begin
      @dbEsta.connection.execute(sql)
    rescue Exception => exc
      redirect_to "/auths/flujos", alert: "No se ha podido borrar el flujo. Error: #{exc.message}"
    end
    redirect_to "/auths/flujos", notice: "Flujo borrado exitosamente"
  end

  private

    def find_flujo
      @id = params[:id].to_s.split("-")
      sql = "SELECT AuthsFlujos.*, '' as NombreUsuario FROM AuthsFlujos WHERE IdTipoSolicitud = #{User.sanitize(@id.first)} AND NivelActual = #{User.sanitize(@id[1])} AND IdUsuario = #{User.sanitize(@id.last)} LIMIT 1"
      @flujo = @dbEsta.connection.select_all(sql).first rescue false
      redirect_to '/' unless @flujo
      if @flujo['IdUsuario'].to_i > 0
        u = User.where("id = #{User.sanitize(@flujo['IdUsuario'])}").first
        @flujo['NombreUsuario'] = u.name rescue 'Usuario No Encontrado'
      end
    end

    def obtiene_catalogos
      @tipo_solicitudes = @dbEsta.connection.select_all("SELECT AuthsTipoSolicitudes.* FROM AuthsTipoSolicitudes ORDER BY IdTipoSolicitud").map{|u| ["#{u['IdTipoSolicitud']} - #{u['Nombre'].to_s}", "#{u['IdTipoSolicitud']}"]}.uniq
      @niveles = [["00 - Creada", "0"]]
      @niveles = @niveles.concat((1..20).map{|i| ["#{format('%02d', i)} - En Proceso Nivel #{i}", "#{i}"]})
      @niveles = @niveles.concat((59..69).map{|i| ["#{i} - Rechazada", "#{i}"]})
      @niveles = @niveles.concat((80..99).map{|i| ["#{i} - Aprobada", "#{i}"]})
      @usuarios = User.joins("LEFT JOIN permisos ON users.id = permisos.idUsuario").where("permisos.id > 0").order(:name).map{|u| ["#{u.name.to_s.gsub(" - ", " ")}", "#{u.id}"]}.uniq
    end

    def create_or_update
      @new = params[:new] == "true"
      @id_tipo_solicitud = params[:idtiposolicitud].to_i
      @nivel_actual = params[:nivelactual].to_i
      @id_usuario = params[:idusuario].to_i
      @debe_autorizar = params[:debeautorizar].to_i
      @nivel_futuro = params[:nivelfuturo].to_i
      @flujo = {}
      @flujo['IdTipoSolicitud'] = @id_tipo_solicitud
      @flujo['NivelActual'] = @nivel_actual
      @flujo['IdUsuario'] = @id_usuario
      @flujo['DebeAutorizar'] = @debe_autorizar
      @flujo['NivelFuturo'] = @nivel_futuro
      sql = "INSERT INTO AuthsFlujos (IdTipoSolicitud, NivelActual, IdUsuario, DebeAutorizar, NivelFuturo) VALUES ( #{User.sanitize(@id_tipo_solicitud)}, #{User.sanitize(@nivel_actual)}, #{User.sanitize(@id_usuario)}, #{User.sanitize(@debe_autorizar)}, #{User.sanitize(@nivel_futuro)} ) ON DUPLICATE KEY UPDATE DebeAutorizar = #{User.sanitize(@debe_autorizar)}, NivelFuturo = #{User.sanitize(@nivel_futuro)}"
      begin
        @dbEsta.connection.execute(sql)
      rescue Exception => exc
        flash[:alert] = "No se ha podido #{@new ? "crear" : "editar"} el flujo. Error: #{exc.message}"
        return render 'edit'
      end
      redirect_to "/auths/flujos/#{@id_tipo_solicitud}-#{@nivel_actual}-#{@id_usuario}", notice: "Flujo #{@new ? "creado" : "editado"} exitosamente"
    end
end

app/controllers/auths/tipo_solicitudes_controller.rb
class Auths::TipoSolicitudesController < ApplicationController
  before_filter :authenticate_user!
  before_filter :admin_only
  before_filter :find_solicitud, only: [:edit, :update, :show, :destroy]
  before_filter :obtiene_catalogos, only: [:new, :create, :edit, :update]

  def index
    sql = "SELECT AuthsTipoSolicitudes.* FROM AuthsTipoSolicitudes ORDER BY IdTipoSolicitud"
    @solicitudes = @dbEsta.connection.select_all(sql)
  end

  def new
    @new = true
    @solicitud = {}
    @solicitud['IdTipoSolicitud'] = 1
    @solicitud['Nombre'] = ''
  end

  def edit
    @new = false
  end

  def create
    create_or_update
  end

  def update
    create_or_update
  end

  def show
  end

  def destroy
    sql = "DELETE FROM AuthsTipoSolicitudes WHERE IdTipoSolicitud = #{User.sanitize(@id.first)} AND Nombre = #{User.sanitize(@id.last)}"
    begin
      @dbEsta.connection.execute(sql)
    rescue Exception => exc
      redirect_to "/auths/solicitudes", alert: "No se ha podido borrar el solicitud. Error: #{exc.message}"
    end
    redirect_to "/auths/solicitudes", notice: "Tipo de Solicitud borrado exitosamente"
  end

  private

    def find_solicitud
      @id = params[:id].to_i
      sql = "SELECT AuthsTipoSolicitudes.* FROM AuthsTipoSolicitudes WHERE IdTipoSolicitud = #{User.sanitize(@id)} LIMIT 1"
      @solicitud = @dbEsta.connection.select_all(sql).first rescue false
      redirect_to '/' unless @solicitud
    end

    def obtiene_catalogos
    end

    def create_or_update
      @new = params[:new] == "true"
      @id_solicitud = params[:idsolicitud].to_i
      @id_solicitud = get_id if @new && @id_solicitud == 0
      @nombre = params[:nombre].to_s
      @solicitud = {}
      @solicitud['IdTipoSolicitud'] = @id_solicitud
      @solicitud['Nombre'] = @nombre
      if @nombre == ''
        flash[:alert] = "Nombre inválido"
        return render 'edit'
      end
      sql = "INSERT INTO AuthsTipoSolicitudes (IdTipoSolicitud, Nombre) VALUES ( #{User.sanitize(@id_solicitud)}, #{User.sanitize(@nombre)} ) ON DUPLICATE KEY UPDATE Nombre = #{User.sanitize(@nombre)}"
      begin
        @dbEsta.connection.execute(sql)
      rescue Exception => exc
        flash[:alert] = "No se ha podido #{@new ? "crear" : "editar"} el tipo de solicitud. Error: #{exc.message}"
        return render 'edit'
      end
      redirect_to "/auths/tipo_solicitudes/#{@id_solicitud}", notice: "Tipo de Solicitud #{@new ? "creado" : "editado"} exitosamente"
    end

    def get_id
      id = 1
      ids = @dbEsta.connection.select_all("SELECT max(IdTipoSolicitud) as mid FROM AuthsTipoSolicitudes")
      id = ids.first['mid'].to_i + 1 if ids.count == 1
      id
    end
end

app/helpers/auths/flujos_helper.rb
module Auths::FlujosHelper
  def get_tipo_solicitud(i)
    return @tipo_solicitudes.select { |item|  item[1] == i.to_s }.first[0] rescue "No encontrado"
  end

  def get_nivel(i)
    return @niveles.select { |item|  item[1] == i.to_s }.first[0] rescue "No encontrado"
  end
end

app/helpers/auths/solicitudes_helper.rb
module Auths::SolicitudesHelper
  def get_usuario(i, d = "No encontrado")
    return @usuarios.select { |item|  item[1] == "#{i}" }.first[0] rescue d
  end

  def get_tipo_solicitud(i)
    return @tipo_solicitudes.select { |item|  item[1] == i.to_s }.first[0] rescue "No encontrado"
  end

  def get_nivel(i)
    return @niveles.select { |item|  item[1] == i.to_s }.first[0] rescue "No encontrado"
  end

  def get_email(i)
    return @emails.select { |item|  item[1] == "#{i}" }.first[0] rescue "No encontrado"
  end
end

app/views/auths/solicitudes/_form.html.erb
<%= form_tag('/auths/solicitudes', multipart: true, class: 'form-horizontal' ) do |f| %>
  <div class="form-inputs loader-form ">
    <%= hidden_field_tag 'new', @new %>

    <br>
    <div class="form-group">
      <label class="control-label col-md-3">Tipo de Solicitud</label>
      <div class="col-md-4 text-right">
        <p><%= select_tag 'idtiposolicitud', options_for_select(@tipo_solicitudes, @solicitud['IdTipoSolicitud']), class: 'form-control' %></p>
      </div>
      <div class="col-md-9 col-md-offset-3">
        <p class="help-block">Seleccione el Tipo de Solicitud a Crear</p>
      </div>
    </div>

    <div class="form-group">
      <label class="control-label col-md-3">Mensaje *</label>
      <div class="col-md-7 text-right">
        <%= text_area_tag 'texto', nil, size: "50x10", class: "form-control", placeholder: "Mensaje" %>
      </div>
      <div class="col-md-9 col-md-offset-3">
        <p class="help-block">Ingrese el Mensaje de la Solicitud</p>
      </div>
    </div>

    <div class="form-group">
      <label class="control-label col-md-3">&nbsp;</label>
      <div class="col-md-7 text-right">
        <hr>
        <%= file_field_tag :file, disabled: true %>
        <p class="help-block">Sólo imágenes (JPEG, JPG, PNG o GIF) o documentos (PDF, DOC, XLS, PPT)</p>
        <p class="help-block">Tamaño máximo: 2 MB (Opcional)</p>
      </div>
    </div>

    <div class="col-md-2 col-md-offset-10">
      <div class="form-actions loader-form text-right">
        <%= link_to "Regresar", auths_solicitudes_path, class: "btn btn-default" %>
        <%= submit_tag "Enviar", class: "btn btn-primary" %>
      </div>
    </div>

    <br>

  </div>
<% end %>


<link href="https://cdnjs.cloudflare.com/ajax/libs/chosen/1.4.2/chosen.min.css" rel="stylesheet" />
<script src="https://cdnjs.cloudflare.com/ajax/libs/chosen/1.4.2/chosen.jquery.min.js"></script>

app/views/auths/solicitudes/_panel_log.html.erb
<div role="tabpanel" class="tab-pane" id="log">
	<div class="panel panel-default">
		<div class="panel-body">
			<div class="row">
				<div class="col-sm-10">
					<h3>Log</h3>
				</div>
			</div>
			<hr>
			<div class="row">
				<div class="col-sm-12">
					<% @solicitud_logs.each do |item| %>
						<p>
							<%= item['FechaCreacion'].to_s[0..19] %>:
							<%= item['Texto'] %>
						</p>
					<% end %>
				</div>
			</div>
		</div>
	</div>
</div>

app/views/auths/solicitudes/index.html.erb
<br>
<%= render(partial: '/auths/navpills') %>

<div class="col-md-12 col-sm-12 center-block inner-top-sm">

	<br>

	<table cellpadding="0" cellspacing="0" border="0" class=" text-center table table-hover table-bordered table-striped">

	  <thead>
      <tr>
				<th><a href="#" data-toggle="tooltip" title="Fecha de Creación de la Solicitud">Fecha</a></th>
	      <th><a href="#" data-toggle="tooltip" title="Tipo de la Solicitud">Tipo</a></th>
	      <th><a href="#" data-toggle="tooltip" title="Mensaje de la Solicitud">Mensaje</a></th>
	      <th><a href="#" data-toggle="tooltip" title="Persona que Solicita">Solicita</a></th>
	      <th><a href="#" data-toggle="tooltip" title="Persona que Autoriza">Autoriza</a></th>
	      <th><a href="#" data-toggle="tooltip" title="Nivel Actual">Nivel</a></th>
        <th></th>
	    </tr>
	  </thead>

    <tbody>
      <% @solicitudes.each do |item| %>
        <% url = "/auths/solicitudes/#{item['IdSolicitud']}" %>
        <tr>
	        <td><%= link_to item['FechaCreacion'].to_s[0..10], url, title: item['FechaCreacion'], data: { toggle: "tooltip" } %></td>
          <td><%= link_to get_tipo_solicitud(item['IdTipoSolicitud']), url, title: get_tipo_solicitud(item['IdTipoSolicitud']), data: { toggle: "tooltip" } %></td>
	        <td><%= link_to item['Texto'].to_s.truncate(30), url, title: item['Texto'], data: { toggle: "tooltip" } %></td>
	        <td><%= get_usuario(item['IdUsuarioSolicitante'], "Ninguno") %></td>
	        <td><%= get_usuario(item['IdUsuarioAutorizador'], "Ninguno") %></td>
          <td><%= get_nivel(item['NivelActual']) %></td>
          <td>
            <%= link_to 'Ver', url, class: 'btn btn-xs btn-primary' %>
          </td>
        </tr>
      <% end %>
	  </tbody>
	</table>

  <%= link_to 'Crear Solicitud', new_auths_solicitude_path, class: "btn btn-primary" %>

</div>

app/views/auths/solicitudes/show.html.erb
<br>
<%= render(partial: '/auths/navpills') %>

<div class="col-md-12 col-sm-12 center-block inner-top-sm">

  <%= render(partial: 'panel_general') %>

  <% if current_user.has_role? :admin %>
    <a class="btn btn-default" role="button" data-toggle="collapse" href="#collapseExample" aria-expanded="false" aria-controls="collapseExample">
      Ver Log
    </a>
    <br>
    <div class="collapse" id="collapseExample">
      <%= render(partial: 'panel_log') %>
    </div>
  <% end %>
</div>

<div class="modal fade" id="agregarFiles" tabindex="-1" role="dialog" aria-labelledby="agregarFilesLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Subir Archivo</h4>
      </div>
      <div class="modal-body">

	    <div class="panel panel-primary">
        <div class="panel-body">
          <%= form_for @solicitudRespuestasFile, url: auths_respuestas_files_path, html: { multipart: true } do |form| %>
            <%= hidden_field_tag 'IdSolicitud', @id %>
            <%= hidden_field_tag 'IdRespuesta', Time.now.to_i %>
            <%= hidden_field_tag 'Usuario', current_user.id %>

            <%= form.file_field :file %>
            <p class="help-block">Sólo imágenes (JPEG, JPG, PNG o GIF) o documentos (PDF, DOC, XLS, PPT)</p>
            <p class="help-block">Tamaño máximo: 2 MB</p>

        </div>
        </div>
        </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
            <%= submit_tag "Subir", class: "btn btn-primary " %>
        <% end %>
      </div>
    </div>
  </div>
</div>

<style>
	.chosen-container {
		width: 100% !important;
	}
	.tab-content {
	    border-left: 1px solid #ddd;
	    border-right: 1px solid #ddd;
	    border-bottom: 1px solid #ddd;
	    padding: 10px;
	}
	.nav-tabs {
	    margin-bottom: 0;
	}

	.respuestas_container {
		background-color: #ECEDEF;
		padding: 5px;
		margin: 10px 0px;
	    border: 1px solid #ddd;
	}

  .message-history {
    margin-left: 220px;
    overflow-y: auto;
    overflow-x: hidden;
    height: 100%;
    padding: 0 18px 1rem 1.5rem;
  }

  .message {
    position: relative;
    margin-top: .7rem;
    padding: .25rem 2rem .1rem 3rem;
    min-height: 36px;
  }

  .message_username {
    font-weight: 900;
    padding-right: .25rem;
    color: #3d3c40 !important;
    margin-left: 0;
    font-style: normal;
    text-decoration: none;
  }

  .message_timestamp {
    text-align: left;
    display: inline;
    position: relative;
    top: 0;
    left: 0;
    color: #babbbf;
    font-size: 12px;
    line-height: 1.2rem;
    width: 36px;
    margin-right: 0;
    margin-left: 0;
  }

  .message_content {
    /*color: #8b898f;*/
    /*font-style: italic;*/
    display: block;
    font-size: 16px;
    min-height: 1rem;
  }
  .message_content img {
    margin: 0 0;
  }
  .message_content span.small {
    font-size: 12px;
  }
  .message_content span.glyphicon {
    font-size: 2em;
  }
</style>