config/routes.rb
  get 'ant_saldos_cliente_datos'         => 'ant_saldos#ant_saldos_cliente_datos'
  post 'ant_saldos_cliente_editar'       => 'ant_saldos#ant_saldos_cliente_editar'
  get 'ant_saldos_cliente_anyo'          => 'ant_saldos#ant_saldos_cliente_anyo'
  get 'ant_saldos_cliente_hist1'         => 'ant_saldos#ant_saldos_cliente_hist1'
  get 'ant_saldos_sucursal'              => 'ant_saldos#ant_saldos_sucursal'
  get 'ant_saldos_detalle'               => 'ant_saldos#ant_saldos_detalle'
  get 'ant_saldos_vencidas'              => 'ant_saldos#ant_saldos_vencidas'
  get 'ant_saldos_comentarios'           => 'ant_saldos#ant_saldos_comentarios'
  get 'ant_saldos_mails'                 => 'ant_saldos#ant_saldos_mails'
  get 'ant_saldos_mails_new'             => 'ant_saldos#ant_saldos_mails_new'
  post 'ant_saldos_mails'                => 'ant_saldos#ant_saldos_mails_create'
  delete 'ant_saldos_mails'              => 'ant_saldos#ant_saldos_mails_delete'
  get 'enviar_mails_de_aclaracion_robot' => 'ant_saldos#enviar_mails_de_aclaracion_robot'
  get 'enviar_mails_de_aclaracion_robot_index' => 'ant_saldos#enviar_mails_de_aclaracion_robot_index'
  get 'ant_saldos_sucursal'              => 'ant_saldos#ant_saldos_sucursal'

  get 'replicasuc'                       => 'replicasuc#replicasuc'

  get 'calc_objetivos'                              => 'calc_objetivos#calc_objetivos'
  get 'calc_objetivos_objetivo'                     => 'calc_objetivos#calc_objetivos_objetivo'
  get 'calc_objetivos_estadistica'                  => 'calc_objetivos#calc_objetivos_estadistica'
  get 'calc_objetivos_analisis'                     => 'calc_objetivos#calc_objetivos_analisis'
  get 'calc_objetivos_ajax_subagrupa'               => 'calc_objetivos#ajax_subagrupa'
  get 'calc_objetivos_ajax_agrupasuc'               => 'calc_objetivos#ajax_agrupasuc'
  get 'calc_objetivos_gridcrecireal_porce_update'   => 'calc_objetivos#calc_objetivos_gridcrecireal_porce_update'
  get 'calc_objetivos_gridcrecireal_obj_update'     => 'calc_objetivos#calc_objetivos_gridcrecireal_obj_update'

  get 'repobjetivos'                     => 'repobjetivos#repobjetivos_zona'
  get 'repobjetivos_zona'                => 'repobjetivos#repobjetivos_zona'
  get 'repobjetivos_suc'                 => 'repobjetivos#repobjetivos_suc'
  get 'repobjetivos_det_suc'             => 'repobjetivos#repobjetivos_det_suc'

  get 'signos_vitales'                   => 'signos_vitales#signos_vitales_zona'
  get 'signos_vitales_zona'              => 'signos_vitales#signos_vitales_zona'
  get 'signos_vitales_suc'               => 'signos_vitales#signos_vitales_suc'
  get 'signos_vitales_graf'              => 'signos_vitales#signos_vitales_graf'

  get 'estaventas'                       => 'estaventas#estaventas'
  get 'estaventas_ajax_subagrupa'        => 'estaventas#ajax_subagrupa'
  get 'estaventas_ajax_agrupasuc'        => 'estaventas#ajax_agrupasuc'

  get 'comprobantes_nomina'                   => 'comprobantes_nomina#index'
  get 'comprobantes_nomina_descarga/:nomcomp' => 'comprobantes_nomina#comprobantes_nomina_descarga'
  get 'comprobantes_nomina_ayuda'             => 'comprobantes_nomina#ayuda'
  get 'contrato_colectivo'                    => 'comprobantes_nomina#contrato_colectivo'

  get 'claves_pdv' => 'claves_pdv#index'

  get 'bajas'         => 'bajas#index'
  get 'bajas_obra'    => 'bajas#bajas_obra'
  get 'bajas_detalle' => 'bajas#bajas_detalle'
  get 'bajas_mails'       => 'bajas#bajas_mails'
  get 'bajas_mails_new'   => 'bajas#bajas_mails_new'
  post 'bajas_mails'      => 'bajas#bajas_mails_create'
  delete 'bajas_mails'    => 'bajas#bajas_mails_delete'
  get 'bajas_enviar_mails_robot' => 'bajas#bajas_enviar_mails_robot'
  get 'bajas_enviar_mails_robot_index' => 'bajas#bajas_enviar_mails_robot_index'
  get 'bajas/export_excel' => 'bajas#export_excel'

  get 'consultas'                => 'consultas#index'
  get 'consultas_reportes'       => 'consultas#reportes'

  get 'reportes_bi'              => 'reportes_bi#index'
  get 'reportes_bi_reportes'     => 'reportes_bi#reportes'

  get 'contenedores'             => 'contenedores#index'
  get 'contenedores_contenedor'  => 'contenedores#contenedor'
  get 'contenedores_mails'       => 'contenedores#contenedores_mails'
  get 'contenedores_mails_new'   => 'contenedores#contenedores_mails_new'
  post 'contenedores_mails'      => 'contenedores#contenedores_mails_create'
  delete 'contenedores_mails'    => 'contenedores#contenedores_mails_delete'
  get 'contenedores_enviar_mails_robot' => 'contenedores#contenedores_enviar_mails_robot'
  get 'contenedores_enviar_mails_robot_index' => 'contenedores#contenedores_enviar_mails_robot_index'

  get  'conciliaciones'          => 'conciliaciones#index'
  get  'conciliacion'            => 'conciliaciones#show'
  get  'conciliaciones_robot'    => 'conciliaciones#robot'

  get 'obras'                    => 'obras#obras'
  get 'obra'                     => 'obras#obra'
  get 'obra_detalle'             => 'obras#obra_detalle'
  post 'obra_new_comment'        => 'obras#obra_new_comment'
  post 'obra_edit_status'        => 'obras#obra_edit_status'
  post 'obra_porc_desc_script'   => 'obras#obra_porc_desc_script'

  get 'bloqueo_tarjetas_club_comex' => 'bloqueo_tarjetas_club_comex#index'
  get 'bloqueo_tarjetas_club_comex_new' => 'bloqueo_tarjetas_club_comex#new'
  post 'bloqueo_tarjetas_club_comex_create' => 'bloqueo_tarjetas_club_comex#create'
  get 'bloqueo_tarjetas_club_comex_detalle' => 'bloqueo_tarjetas_club_comex#show'
  post 'bloqueo_tarjetas_club_comex_update' => 'bloqueo_tarjetas_club_comex#update'

  get  'todos'                   => 'todos#todos'
  get  'todos_new'               => 'todos#todos_new'
  post 'todos_create'            => 'todos#todos_create'
  post 'todos_update'            => 'todos#todos_update'
  post 'todos_respuesta_create'  => 'todos#todos_respuesta_create'
  get  'todos_show'              => 'todos#todos_show'
  get  'todos_involucrados_edit' => 'todos#todos_involucrados_edit'
  post 'todos_involucrados_edit_post' => 'todos#todos_involucrados_edit_post'
  resources :todos_respuestas_files

  get  'tickets'                   => 'tickets#tickets'
  get  'tickets_new'               => 'tickets#tickets_new'
  post 'tickets_create'            => 'tickets#tickets_create'
  post 'tickets_update'            => 'tickets#tickets_update'
  post 'tickets_respuesta_create'  => 'tickets#tickets_respuesta_create'
  get  'tickets_show'              => 'tickets#tickets_show'
  get  'tickets_involucrados_edit' => 'tickets#tickets_involucrados_edit'
  post 'tickets_involucrados_edit_post' => 'tickets#tickets_involucrados_edit_post'
  get  'tickets_assign_myself'     => 'tickets#tickets_update'
  get  'tickets_programados'       => 'tickets#tickets_programados'
  get  'tickets_programados_new'   => 'tickets#tickets_programados_new'
  post 'tickets_programados_create'=> 'tickets#tickets_programados_create'
  get  'tickets_programados_edit'  => 'tickets#tickets_programados_edit'
  post 'tickets_programados_update'=> 'tickets#tickets_programados_update'
  delete 'tickets_programados_destroy' => 'tickets#tickets_programados_destroy'
  get  'tickets_programados_robot' => 'tickets#tickets_programados_robot'
  resources :tickets_respuestas_files, only: [:create]

  get  'revisiones'                => 'revisiones#revisiones'
  get  'revisiones_new'            => 'revisiones#revisiones_new'
  post 'revisiones_create_preview' => 'revisiones#revisiones_create_preview'
  post 'revisiones_create'         => 'revisiones#revisiones_create'
  get  'revisiones_show'           => 'revisiones#revisiones_show'

  get  'grupos'                   => 'grupos#grupos'
  get  'grupos_new'               => 'grupos#grupos_new'
  post 'grupos_create'            => 'grupos#grupos_create'
  get  'grupos_edit'              => 'grupos#grupos_edit'
  post 'grupos_update'            => 'grupos#grupos_update'
  delete 'grupos_destroy'         => 'grupos#grupos_destroy'
  get  'grupos_update_rol'        => 'grupos#grupos_update_rol'

  namespace :supervisiones do
    root :to                        => 'supervisiones#root'

    get  'programadas'              => 'supervisiones#programadas'
    get  'terminadas'               => 'supervisiones#terminadas'
    get  'supervision_terminada'    => 'supervisiones#supervision_terminada'
    get  'crear_supervision'        => 'supervisiones#crear_supervision'
    get  'realizar_supervision'     => 'supervisiones#crear_supervision'
    get  'nueva_supervision'        => 'supervisiones#nueva_supervision'
    post 'nueva_supervision'        => 'supervisiones#nueva_supervision_create'
    get  'supervision_en_curso'     => 'supervisiones#supervision_en_curso'
    post 'supervision_en_curso'     => 'supervisiones#supervision_en_curso_update'
    get  'supervision_en_curso_aci' => 'supervisiones#supervision_en_curso_aci'
    post 'supervision_en_curso_aci' => 'supervisiones#supervision_en_curso_aci_create'
    get  'supervisiones_en_curso'   => 'supervisiones#supervisiones_en_curso'
    get  'supervision_por_aprobar'  => 'supervisiones#supervision_por_aprobar'
    post 'supervision_por_aprobar'  => 'supervisiones#supervision_por_aprobar_update'
    get  'supervisiones_por_aprobar'=> 'supervisiones#supervisiones_por_aprobar'
    get  'supervisiones_por_programar' => 'supervisiones#supervisiones_por_programar'
    get  'programar_supervisiones'  => 'supervisiones#programar_supervisiones'
    post 'programar_supervisiones'  => 'supervisiones#programar_supervisiones_create'
    delete 'programar_supervisiones'=> 'supervisiones#programar_supervisiones_destroy'

    get  'checklists'               => 'checklists#index'
    get  'checklist_new'            => 'checklists#new'
    post 'checklist_create'         => 'checklists#create'
    get  'checklist_edit'           => 'checklists#edit'
    post 'checklist_update'         => 'checklists#update'

app/views/obras/obra.html.erb
<h1 class="text-center">Movimientos Asociados a la Obra</h1>

<% if @obra && @obra.count > 0 %>
  <p>
    <b>Sucursal:</b> <%= @obra['Sucursal'] %> - <%= @obra['sNombre'] %>, <b>Obra:</b> <%= @obra['IdObra'] %> - <%= @obra['Nombre'] %><br>
    <b>Total Vendido:</b> <%= number_to_currency(@GTotalVendido, :locale => :mx, :precision => 2) %>, <b>Total Valuado:</b> <%= number_to_currency(@GTotalValuado, :locale => :mx, :precision => 2) %>, <b>Descuento Equivalente:</b> <%= number_to_currency(@GDescuentoEquivalente, :locale => :mx, :precision => 2).gsub("$","") %>%
  </p>  
<% end %>


<div class="col-md-12 col-sm-12 center-block inner-top-sm">

  <small>
    <%= link_to "Regresar", "/obras" %>
  </small>
  <br />
  <br />

  <table cellpadding="0" cellspacing="0" border="0" class="table table-hover table-bordered table-striped text-center" id="">
    <thead>
      <tr>
        <th><a href="#" data-toggle="tooltip" title="Fecha de la Factura">Fecha</a></th>
        <th><a href="#" data-toggle="tooltip" title="Número de Movimiento">Nummov</a></th>
        <th><a href="#" data-toggle="tooltip" title="Control de la Factura">Control</a></th>
        <th><a href="#" data-toggle="tooltip" title="Tipo Subtipo">Tipo</a></th>
        <th><a href="#" data-toggle="tooltip" title="Nombre del Cliente">Cliente</a></th>
        <th><a href="#" data-toggle="tooltip" title="Identificador del Vendedor">Vdor</a></th>
        <th><a href="#" data-toggle="tooltip" title="Importe Total">Total</a></th>
        <th><a href="#" data-toggle="tooltip" title="Importe Total Vendido">Vendido</a></th>
        <th><a href="#" data-toggle="tooltip" title="Importe Total Valuado">Valuado</a></th>
        <th><a href="#" data-toggle="tooltip" title="Lleva Mano">Mano</a></th>
      </tr>
    </thead>
    <tbody>
      <% @movs.each do |m| %>
        <tr>
          <% url = "/obra_detalle?sucursal=#{@sucursal}&idobra=#{@idobra}&fecha=#{m['Fecha']}&nummov=#{m['Nummov']}" %>
          <td><%= link_to fix_show_date(m['Fecha']), url %></td>
          <td><%= link_to m['Nummov'], url %></td>
          <td><%= link_to m['Controlfac'], url %></td>
          <td><%= m['Tipo_subt'] %> - <%= m['NomTipoSubTipo'] %></td>
          <td><%= m['cNombre'] %></td>
          <td><%= m['Idvendedor'] %></td>
          <td><%= number_to_currency(m['Total'], :locale => :mx, :precision => 2) %></td>
          <td><%= m['TotalVendido'] != 0 ? number_to_currency(m['TotalVendido'], :locale => :mx, :precision => 2) : "" %></td>
          <td><%= m['TotalValuado'] != 0 ? number_to_currency(m['TotalValuado'], :locale => :mx, :precision => 2) : "" %></td>
          <td><%= m['Mano'] %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br />

  <div class="col-md-6 col-sm-6">
    <div class="panel panel-primary">
      <div class="panel-heading">
        <h3 class="panel-title text-center">Comentarios</h3>
      </div>
      <div class="panel-body text-right">
        <div id="message-history">
          <% @chat_comments.each do |comment| %>
            <div class="message">
                <% if !comment['userName'].nil? %>
                  <a href="mailto:<%= comment['userEmail'] %>" class="message_username"><%= comment['userName'].to_s.gsub(" - ", " ") %></a>
                <% end %>
                <span class="message_timestamp"><%= comment['FechaHora'].to_s(:db)[0..19] %></span>
                <span class="message_content"><%= comment['Comentario'] %></span>
            </div>                
          <% end %>
        </div>
        <%= form_tag(obra_new_comment_path, class: 'form-horizontal' )  do |f| %>
          <%= hidden_field_tag 'sucursal', @sucursal %>
          <%= hidden_field_tag 'idobra', @idobra %>

          <div class="form-group">
            <div class="col-md-6 col-sm-6">
              <br>
              <%= text_area_tag 'nuevo_comentario', nil, size: "50x3", class: "form-control", placeholder: "Nuevo Comentario" %>
            </div>
          </div>
          <button type="submit" class="btn btn-info">Agregar Comentario</button>
        <% end %>
      </div>
    </div>
  </div>

  <div class="col-md-6 col-sm-6">
    <div class="panel panel-primary">
      <div class="panel-heading">
        <h3 class="panel-title text-center">Descuento Negociado y Status</h3>
      </div>
      <div class="panel-body">
        <center>

          <% if @obra %>
            <h4>Porcentaje de Descuento Negociado: <%= number_to_currency(@obra['PorcDescNegociado'], :locale => :mx, :precision => 2).gsub("$","") %>%</h4>
            <h4>Status Obra Abierta o Cerrada: <%= @obra['Cerrada'].to_i > 0 ? "Cerrada" : "Abierta" %></h4>
            <br>
            <% if @puede_editar %>
              <button type="button" class="btn btn-info" data-toggle="modal" data-target="#myModal">
                Editar
              </button>
            <% end %>
          <% else %>
            <h4>Sin Datos</h4>
          <% end %>

        </center>
      </div>
    </div>                
  </div>

  <% if @puede_editar %>

    <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <h4 class="modal-title" id="myModalLabel">Descuento Negociado y Status Propuestos</h4>
          </div>

          <%= form_tag(obra_edit_status_path, class: 'form-horizontal' )  do |f| %>

            <div class="modal-body">
              <div class="ref-group">

                <%= hidden_field_tag 'sucursal', @sucursal %>
                <%= hidden_field_tag 'idobra', @idobra %>

                <div class="form-group">
                  <label class="col-sm-4 control-label">Descuento Negociado</label>
                  <div class="col-md-6 col-sm-6">
                    <%= text_field_tag 'descuento_negociado', number_to_currency(@GDescuentoEquivalente, :locale => :mx, :precision => 2).gsub("$",""), class: "form-control", placeholder: "0.00%" %>
                  </div>
                </div>

                <div class="form-group">
                  <label class="col-sm-4 control-label">Status de la Obra</label>
                  <div class="col-md-6 col-sm-6">
                    <% @statuses = [ { "id" => 0, "status" => "Abierta" }, { "id" => 1, "status" => "Cerrada" } ] %> 
                    <%= select_tag 'status', options_for_select(@statuses.collect{|t| [ t['status'], t['id'] ]}, 1), label: false, placeholder: "Status Abierta o Cerrada", class: 'form-control' %>                    
                  </div>
                </div>

              </div>
            </div>
  
            <div class="modal-footer">
              <button type="button" class="btn btn-info" data-dismiss="modal">Cancelar</button>
              <button type="submit" class="btn btn-primary">Guardar</button>
            </div>

          <% end %>

        </div>
      </div>
    </div>

  <% end %>

</div>

<style>

  .glyphicon-ok {
    color: green;
  }

  .message-history {
    margin-left: 220px;
    overflow-y: auto;
    overflow-x: hidden;
    height: 100%;
    padding: 0 18px 1rem 1.5rem;
  }

  .message {
    position: relative;
    margin-top: .7rem;
    padding: .25rem 2rem .1rem 3rem;
    min-height: 36px;
  }

  .message_username {
    font-weight: 900;
    padding-right: .25rem;
    color: #3d3c40 !important;
    margin-left: 0;
    font-style: normal;
    text-decoration: none;
  }

  .message_timestamp {
    text-align: left;
    display: inline;
    position: relative;
    top: 0;
    left: 0;
    color: #babbbf;
    font-size: 12px;
    line-height: 1.2rem;
    width: 36px;
    margin-right: 0;
    margin-left: 0;
  }

  .message_content {
    /*color: #8b898f;*/
    /*font-style: italic;*/
    display: block;
    font-size: 16px;
    min-height: 1rem;
  }

</style>

app/views/obras/obras.html.erb
<h1 class="text-center">Obras</h1>

<div class="pull-right text-right">
  <small>
    <% if @puede_editar %>
      <%= form_tag(obra_porc_desc_script_path) do |f| %>
        <button type="submit" class="btn btn-xs btn-primary" data-confirm='Está seguro que desea ejecutar el script para el Porcentaje de Descuento Calculado?'>Calcular Porcentaje de Descuento</button>
      <% end %>
    <% end %>
      <%= @ver_activas_abiertas == false ? "Todas" : raw("<a href='/obras/?ver_activas_abiertas=2'>Todas</a>") %> |
      <%= @ver_activas_abiertas == "1" ? "Ver Activas" : raw("<a href='/obras/'>Ver Activas</a>") %> |
      <%= @ver_activas_abiertas == "0" ? "Ver Inactivas" : raw("<a href='/obras/?ver_activas_abiertas=0'>Ver Inactivas</a>") %> |
      <%= @ver_activas_abiertas == "3" ? "Ver Abiertas" : raw("<a href='/obras/?ver_activas_abiertas=3'>Ver Abiertas</a>") %> |
      <%= @ver_activas_abiertas == "4" ? "Ver Cerradas" : raw("<a href='/obras/?ver_activas_abiertas=4'>Ver Cerradas</a>") %>
    <br>
    <br>
  </small>
</div>

<div class="col-md-12 col-sm-12 center-block inner-top-sm">


  <table cellpadding="0" cellspacing="0" border="0" class="table table-hover table-bordered table-striped text-center" id="example">

    <thead>
      <tr>
        <th><a href="#" data-toggle="tooltip" title="Número de la Sucursal">Suc</a></th>
        <th><a href="#" data-toggle="tooltip" title="Nombre de la Sucursal">Sucursal</a></th>
        <th><a href="#" data-toggle="tooltip" title="Id de la Obra">Obra</a></th>
        <th><a href="#" data-toggle="tooltip" title="Nombre de la Obra">Nombre</a></th>
        <th><a href="#" data-toggle="tooltip" title="Fecha de Inicio de la Obra">Inicio</a></th>
        <th><a href="#" data-toggle="tooltip" title="Fecha del Último Movimiento">Ult Mov</a></th>
        <th><a href="#" data-toggle="tooltip" title="Fecha de Cierre de la Obra">Cierre</a></th>
        <th><a href="#" data-toggle="tooltip" title="Porcentaje de Descuento Calculado">% Calc</a></th>
        <th><a href="#" data-toggle="tooltip" title="Porcentaje de Descuento Negociado">% Neg</a></th>
        <th><a href="#" data-toggle="tooltip" title="Calificación de la Obra">Calif</a></th>
        <th><a href="#" data-toggle="tooltip" title="Status de la Obra Activa o Inactiva">Status</a></th>
        <th><a href="#" data-toggle="tooltip" title="Status de la Obra Abierta o Cerrada">Cerrada</a></th>
      </tr>
    </thead>
    <tbody>

      <% @obras.each do |m| %>
        <tr>
          <% url = "/obra?sucursal=#{m['Sucursal']}&idobra=#{m['IdObra']}" %>
          <td><%= link_to "#{m['Sucursal']}", url %></td>
          <td><%= link_to "#{m['sNombre']}", url %></td>
          <td><%= link_to "#{m['IdObra']}", url %></td>
          <td><%= link_to "#{m['Nombre']}", url %></td>
          <td><%= "#{fix_show_date(m['FechaIni'])}" %></td>
          <td><%= "#{fix_show_date(m['FechaUltMov'])}" %></td>
          <td><%= "#{fix_show_date(m['FecUltMovCierre'])}" %></td>
          <td><%= number_to_currency(m['PorcDescCalculado'], :locale => :mx, :precision => 2).gsub("$","") %>%</td>
          <td><%= number_to_currency(m['PorcDescNegociado'], :locale => :mx, :precision => 2).gsub("$","") %>%</td>
          <td><%= m['Calificación'].to_s != "" ? m['Calificación'] : "" %></td>
          <td><%= m['Activa'].to_i > 0 ? "Activa" : "Inactiva" %></td>
          <td><%= m['Cerrada'].to_i > 0 ? "Cerrada" : "Abierta" %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <br />


</div>


<script src="/js/jquery.dataTables.min.js"></script>
<script src="/js/dataTables.bootstrap4.min.js"></script>


<style type="text/css">
label{
  display: none;
}
.dataTables_filter.md-form {
    margin-top: .55rem;
}
.dataTables_filter.md-form input{
    font-weight: 300;
}
.dataTables_wrapper .row {
    margin-bottom: 1.5rem;
}
div.dataTables_wrapper div.dataTables_info {
    padding-top: 0;
    padding-bottom: 1rem;
}
.dataTables_paginate {
    float: right;
}
.dataTables_filter {
    float: right;
}
</style>

<script type="text/javascript">
$(document).ready(function() {
  $('#example').DataTable({"pageLength": 100 });
  $('.dataTables_wrapper').find('label').each(function() {
    $(this).parent().append($(this).children());
  });
  $('.dataTables_filter').find('input').each(function() {
    $('input').attr("placeholder", "Buscar");
    $('input').removeClass('form-control-sm');
  });
  $('.dataTables_length').addClass('d-flex flex-row');
  $('.dataTables_filter').addClass('md-form');
  $('select').addClass('mdb-select');
  $('.mdb-select').removeClass('form-control form-control-sm');
  $('.dataTables_filter').find('label').remove();
});
</script>