config/routes.rb
  get '/delete_taskuser'                 => 'homereportes#delete_taskuser'
  get '/edit_taskuser'                   => 'homereportes#edit_taskuser'
  post '/update_taskuser'                => 'homereportes#update_taskuser'
  post '/checkjefes'                     => 'homereportes#checkjefes'
  get '/edit_task'                       => 'homereportes#edit_task'
  post '/update_task'                    => 'homereportes#update_task'

  post '/zammad_create'                  => 'home#zammad_create'
  get '/privacy'                         => 'home#privacy'
  get '/ayuda'                           => 'home#ayuda'
  get '/personalizar_menu'               => 'home#personalizar_menu'
  get '/personalizar_menu_t'             => 'home#personalizar_menu_t'


  get 'checadores/enviar_chequeos' => 'checadores#enviar_chequeos'
  #get 'checadores/index'

  get '/app_rol_nivel'                   => 'app_rol_nivel#index'
  get '/app_rol_nivel_acceso'            => 'app_rol_nivel#app_rol_nivel_acceso'

  get 'ant_saldos'                       => 'ant_saldos#ant_saldos'
  get 'ant_saldos_clientes'              => 'ant_saldos#ant_saldos_clientes'
  get 'ant_saldos_clientes_nombre_rfc'   => 'ant_saldos#ant_saldos_clientes_nombre_rfc'
  get 'ant_saldos_cliente'               => 'ant_saldos#ant_saldos_cliente'
  get 'ant_saldos_cliente_datos'         => 'ant_saldos#ant_saldos_cliente_datos'
  post 'ant_saldos_cliente_editar'       => 'ant_saldos#ant_saldos_cliente_editar'
  get 'ant_saldos_cliente_anyo'          => 'ant_saldos#ant_saldos_cliente_anyo'
  get 'ant_saldos_cliente_hist1'         => 'ant_saldos#ant_saldos_cliente_hist1'
  get 'ant_saldos_sucursal'              => 'ant_saldos#ant_saldos_sucursal'
  get 'ant_saldos_detalle'               => 'ant_saldos#ant_saldos_detalle'
  get 'ant_saldos_vencidas'              => 'ant_saldos#ant_saldos_vencidas'
  get 'ant_saldos_comentarios'           => 'ant_saldos#ant_saldos_comentarios'
  get 'ant_saldos_mails'                 => 'ant_saldos#ant_saldos_mails'
  get 'ant_saldos_mails_new'             => 'ant_saldos#ant_saldos_mails_new'
  post 'ant_saldos_mails'                => 'ant_saldos#ant_saldos_mails_create'
  delete 'ant_saldos_mails'              => 'ant_saldos#ant_saldos_mails_delete'
  get 'enviar_mails_de_aclaracion_robot' => 'ant_saldos#enviar_mails_de_aclaracion_robot'
  get 'enviar_mails_de_aclaracion_robot_index' => 'ant_saldos#enviar_mails_de_aclaracion_robot_index'
  get 'ant_saldos_sucursal'              => 'ant_saldos#ant_saldos_sucursal'

  get 'replicasuc'                       => 'replicasuc#replicasuc'

  get 'calc_objetivos'                              => 'calc_objetivos#calc_objetivos'
  get 'calc_objetivos_objetivo'                     => 'calc_objetivos#calc_objetivos_objetivo'
  get 'calc_objetivos_estadistica'                  => 'calc_objetivos#calc_objetivos_estadistica'
  get 'calc_objetivos_analisis'                     => 'calc_objetivos#calc_objetivos_analisis'
  get 'calc_objetivos_ajax_subagrupa'               => 'calc_objetivos#ajax_subagrupa'
  get 'calc_objetivos_ajax_agrupasuc'               => 'calc_objetivos#ajax_agrupasuc'
  get 'calc_objetivos_gridcrecireal_porce_update'   => 'calc_objetivos#calc_objetivos_gridcrecireal_porce_update'
  get 'calc_objetivos_gridcrecireal_obj_update'     => 'calc_objetivos#calc_objetivos_gridcrecireal_obj_update'

  get 'repobjetivos'                     => 'repobjetivos#repobjetivos_zona'
  get 'repobjetivos_zona'                => 'repobjetivos#repobjetivos_zona'
  get 'repobjetivos_suc'                 => 'repobjetivos#repobjetivos_suc'
  get 'repobjetivos_det_suc'             => 'repobjetivos#repobjetivos_det_suc'

  get 'signos_vitales'                   => 'signos_vitales#signos_vitales_zona'
  get 'signos_vitales_zona'              => 'signos_vitales#signos_vitales_zona'
  get 'signos_vitales_suc'               => 'signos_vitales#signos_vitales_suc'
  get 'signos_vitales_graf'              => 'signos_vitales#signos_vitales_graf'

  get 'estaventas'                       => 'estaventas#estaventas'
  get 'estaventas_ajax_subagrupa'        => 'estaventas#ajax_subagrupa'
  get 'estaventas_ajax_agrupasuc'        => 'estaventas#ajax_agrupasuc'

  get 'comprobantes_nomina'                   => 'comprobantes_nomina#index'
  get 'comprobantes_nomina_descarga/:nomcomp' => 'comprobantes_nomina#comprobantes_nomina_descarga'
  get 'comprobantes_nomina_ayuda'             => 'comprobantes_nomina#ayuda'
  get 'contrato_colectivo'                    => 'comprobantes_nomina#contrato_colectivo'

  get 'claves_pdv' => 'claves_pdv#index'

  get 'bajas'         => 'bajas#index'
  get 'bajas_obra'    => 'bajas#bajas_obra'
  get 'bajas_detalle' => 'bajas#bajas_detalle'
  get 'bajas_mails'       => 'bajas#bajas_mails'
  get 'bajas_mails_new'   => 'bajas#bajas_mails_new'
  post 'bajas_mails'      => 'bajas#bajas_mails_create'
  delete 'bajas_mails'    => 'bajas#bajas_mails_delete'
  get 'bajas_enviar_mails_robot' => 'bajas#bajas_enviar_mails_robot'
  get 'bajas_enviar_mails_robot_index' => 'bajas#bajas_enviar_mails_robot_index'
  get 'bajas/export_excel' => 'bajas#export_excel'

  get 'consultas'                => 'consultas#index'
  get 'consultas_reportes'       => 'consultas#reportes'

  get 'reportes_bi'              => 'reportes_bi#index'
  get 'reportes_bi_reportes'     => 'reportes_bi#reportes'

  get 'contenedores'             => 'contenedores#index'
  get 'contenedores_contenedor'  => 'contenedores#contenedor'
  get 'contenedores_mails'       => 'contenedores#contenedores_mails'
  get 'contenedores_mails_new'   => 'contenedores#contenedores_mails_new'
  post 'contenedores_mails'      => 'contenedores#contenedores_mails_create'
  delete 'contenedores_mails'    => 'contenedores#contenedores_mails_delete'
  get 'contenedores_enviar_mails_robot' => 'contenedores#contenedores_enviar_mails_robot'
  get 'contenedores_enviar_mails_robot_index' => 'contenedores#contenedores_enviar_mails_robot_index'

  get  'conciliaciones'          => 'conciliaciones#index'
  get  'conciliacion'            => 'conciliaciones#show'
  get  'conciliaciones_robot'    => 'conciliaciones#robot'

  get 'obras'                    => 'obras#obras'
  get 'obra'                     => 'obras#obra'
  get 'obra_detalle'             => 'obras#obra_detalle'
  post 'obra_new_comment'        => 'obras#obra_new_comment'
  post 'obra_edit_status'        => 'obras#obra_edit_status'
  post 'obra_porc_desc_script'   => 'obras#obra_porc_desc_script'

  get 'bloqueo_tarjetas_club_comex' => 'bloqueo_tarjetas_club_comex#index'
  get 'bloqueo_tarjetas_club_comex_new' => 'bloqueo_tarjetas_club_comex#new'
  post 'bloqueo_tarjetas_club_comex_create' => 'bloqueo_tarjetas_club_comex#create'
  get 'bloqueo_tarjetas_club_comex_detalle' => 'bloqueo_tarjetas_club_comex#show'
  post 'bloqueo_tarjetas_club_comex_update' => 'bloqueo_tarjetas_club_comex#update'

  get  'todos'                   => 'todos#todos'
  get  'todos_new'               => 'todos#todos_new'
  post 'todos_create'            => 'todos#todos_create'
  post 'todos_update'            => 'todos#todos_update'
  post 'todos_respuesta_create'  => 'todos#todos_respuesta_create'
  get  'todos_show'              => 'todos#todos_show'
  get  'todos_involucrados_edit' => 'todos#todos_involucrados_edit'
  post 'todos_involucrados_edit_post' => 'todos#todos_involucrados_edit_post'
  resources :todos_respuestas_files

  get  'tickets'                   => 'tickets#tickets'
  get  'tickets_new'               => 'tickets#tickets_new'
  post 'tickets_create'            => 'tickets#tickets_create'
  post 'tickets_update'            => 'tickets#tickets_update'
  post 'tickets_respuesta_create'  => 'tickets#tickets_respuesta_create'
  get  'tickets_show'              => 'tickets#tickets_show'
  get  'tickets_involucrados_edit' => 'tickets#tickets_involucrados_edit'
  post 'tickets_involucrados_edit_post' => 'tickets#tickets_involucrados_edit_post'
  get  'tickets_assign_myself'     => 'tickets#tickets_update'
  get  'tickets_programados'       => 'tickets#tickets_programados'
  get  'tickets_programados_new'   => 'tickets#tickets_programados_new'
  post 'tickets_programados_create'=> 'tickets#tickets_programados_create'
  get  'tickets_programados_edit'  => 'tickets#tickets_programados_edit'
  post 'tickets_programados_update'=> 'tickets#tickets_programados_update'
  delete 'tickets_programados_destroy' => 'tickets#tickets_programados_destroy'
  get  'tickets_programados_robot' => 'tickets#tickets_programados_robot'
  resources :tickets_respuestas_files, only: [:create]

  get  'revisiones'                => 'revisiones#revisiones'
  get  'revisiones_new'            => 'revisiones#revisiones_new'
  post 'revisiones_create_preview' => 'revisiones#revisiones_create_preview'
  post 'revisiones_create'         => 'revisiones#revisiones_create'
  get  'revisiones_show'           => 'revisiones#revisiones_show'

  get  'grupos'                   => 'grupos#grupos'
  get  'grupos_new'               => 'grupos#grupos_new'
  post 'grupos_create'            => 'grupos#grupos_create'
  get  'grupos_edit'              => 'grupos#grupos_edit'
  post 'grupos_update'            => 'grupos#grupos_update'
  delete 'grupos_destroy'         => 'grupos#grupos_destroy'
  get  'grupos_update_rol'        => 'grupos#grupos_update_rol'

  namespace :supervisiones do
    root :to                        => 'supervisiones#root'

    get  'programadas'              => 'supervisiones#programadas'
    get  'terminadas'               => 'supervisiones#terminadas'
    get  'supervision_terminada'    => 'supervisiones#supervision_terminada'
    get  'crear_supervision'        => 'supervisiones#crear_supervision'
    get  'realizar_supervision'     => 'supervisiones#crear_supervision'
    get  'nueva_supervision'        => 'supervisiones#nueva_supervision'
    post 'nueva_supervision'        => 'supervisiones#nueva_supervision_create'

app/views/repobjetivos/repobjetivos_det_suc.html.erb
<center>
<div class="col-md-12 col-sm-12 center-block inner-top-sm">
  <% if @continua > 0 %>

    <h3>Sucursal: <%= @suc + "-" + @nomsuc[0]['Nombre'] %></h3>
    <br>
    <% if @objventasdetsuc.count > 0 %>
      <table cellpadding="0" cellspacing="0" border="0" class="table table-hover table-bordered table-striped" id="example">

        <thead>
          <tr>
          <th bgcolor="FFCC99" colspan=10><a><P align=Center>COMPARATIVO DEL MES DE <%=@nommes%> </a></th>
          </tr>
          <tr>
          <th><a> </a></th>
          <th bgcolor="CCCCCC" colspan=4><a href="#" data-toggle="tooltip" title="Año actual"><P align=Center>Año <%=@anoactual%></a></th>
          <th><a> </a></th>
          <th bgcolor="CCCCCC" colspan=4><a href="#" data-toggle="tooltip" title="Año anterior"><P align=Center>Año <%=@anoanterior%></a></th>
          </tr>
          <tr>
          <th><a> </a></th>
          <th><a href="#" data-toggle="tooltip" title="Total"><P align=Center>Total</a></th>
          <th><a href="#" data-toggle="tooltip" title="Público en General"><P align=Center>Público en Gral.</a></th>
          <th><a href="#" data-toggle="tooltip" title="Cliente con Descto."><P align=Center>Cliente c/Descto.</a></th>
          <th><a href="#" data-toggle="tooltip" title="a Crédito"><P align=Center>a Crédito</a></th>
          <th><a> </a></th>
          <th><a href="#" data-toggle="tooltip" title="Total"><P align=Center>Total</a></th>
          <th><a href="#" data-toggle="tooltip" title="Público en General"><P align=Center>Público en Gral.</a></th>
          <th><a href="#" data-toggle="tooltip" title="Cliente con Descto."><P align=Center>Cliente c/Descto.</a></th>
          <th><a href="#" data-toggle="tooltip" title="a Crédito"><P align=Center>a Crédito</a></th>
          </tr>
        </thead>

        <tbody>
          <% vtaNetaAct=0, vtaNetaContGralAct=0, vtaNetaContCliDesAct=0, vtaNetaCreditoAct=0 %>
          <% vtaCostoAct=0, vtaCostoContGralAct=0, vtaCostoContCliDesAct=0, vtaCostoCreditoAct=0 %>
          <% mUtilAct=0, mUtilContGralAct=0, mUtilContCliDesAct=0, mUtilCreditoAct=0 %>
          <% ticketsAct=0, ticketsContGralAct=0, ticketsContCliDesAct=0, ticketsCreditoAct=0 %>
          <% renglonesAct=0, renglonesContGralAct=0, renglonesContCliDesAct=0, renglonesCreditoAct=0 %>
          <% articulosAct=0, articulosContGralAct=0, articulosContCliDesAct=0, articulosCreditoAct=0 %>
          <% vtaNetaAnt=0, vtaNetaContGralAnt=0, vtaNetaContCliDesAnt=0, vtaNetaCreditoAnt=0 %>
          <% vtaCostoAnt=0, vtaCostoContGralAnt=0, vtaCostoContCliDesAnt=0, vtaCostoCreditoAnt=0 %>
          <% mUtilAnt=0, mUtilContGralAnt=0, mUtilContCliDesAnt=0, mUtilCreditoAnt=0 %>
          <% ticketsAnt=0, ticketsContGralAnt=0, ticketsContCliDesAnt=0, ticketsCreditoAnt=0 %>
          <% renglonesAnt=0, renglonesContGralAnt=0, renglonesContCliDesAnt=0, renglonesCreditoAnt=0 %>
          <% articulosAnt=0, articulosContGralAnt=0, articulosContCliDesAnt=0, articulosCreditoAnt=0 %>
          <% @objventasdetsuc.each do |m| %>
            <% if m['mes'] == @anomesactual %>
              <% vtaNetaAct = m['vtaNeta'] %>
              <% vtaNetaContGralAct = m['vtaNetaContGral'] %>
              <% vtaNetaContCliDesAct = m['vtaNetaContCliDes'] %>
              <% vtaNetaCreditoAct = m['vtaNetaCredito'] %>
              <% vtaCostoAct = m['vtaCosto'] %>
              <% vtaCostoContGralAct = m['vtaCostoContGral'] %>
              <% vtaCostoContCliDesAct = m['vtaCostoContCliDes'] %>
              <% vtaCostoCreditoAct = m['vtaCostoCredito'] %>
              <% mUtilAct = m['mUtil'] %>
              <% mUtilContGralAct = m['mUtilContGral'] %>
              <% mUtilContCliDesAct = m['mUtilContCliDes'] %>
              <% mUtilCreditoAct = m['mUtilCredito'] %>
              <% ticketsAct = m['tickets'] %>
              <% ticketsContGralAct = m['ticketsContGral'] %>
              <% ticketsContCliDesAct = m['ticketsContCliDes'] %>
              <% ticketsCreditoAct = m['ticketsCredito'] %>
              <% renglonesAct = m['renglones'] %>
              <% renglonesContGralAct = m['renglonesContGral'] %>
              <% renglonesContCliDesAct = m['renglonesContCliDes'] %>
              <% renglonesCreditoAct = m['renglonesCredito'] %>
              <% articulosAct = m['articulos'] %>
              <% articulosContGralAct = m['articulosContGral'] %>
              <% articulosContCliDesAct = m['articulosContCliDes'] %>
              <% articulosCreditoAct = m['articulosCredito'] %>
            <% else %>
              <% vtaNetaAnt = m['vtaNeta'] %>
              <% vtaNetaContGralAnt = m['vtaNetaContGral'] %>
              <% vtaNetaContCliDesAnt = m['vtaNetaContCliDes'] %>
              <% vtaNetaCreditoAnt = m['vtaNetaCredito'] %>
              <% vtaCostoAnt = m['vtaCosto'] %>
              <% vtaCostoContGralAnt = m['vtaCostoContGral'] %>
              <% vtaCostoContCliDesAnt = m['vtaCostoContCliDes'] %>
              <% vtaCostoCreditoAnt = m['vtaCostoCredito'] %>
              <% mUtilAnt = m['mUtil'] %>
              <% mUtilContGralAnt = m['mUtilContGral'] %>
              <% mUtilContCliDesAnt = m['mUtilContCliDes'] %>
              <% mUtilCreditoAnt = m['mUtilCredito'] %>
              <% ticketsAnt = m['tickets'] %>
              <% ticketsContGralAnt = m['ticketsContGral'] %>
              <% ticketsContCliDesAnt = m['ticketsContCliDes'] %>
              <% ticketsCreditoAnt = m['ticketsCredito'] %>
              <% renglonesAnt = m['renglones'] %>
              <% renglonesContGralAnt = m['renglonesContGral'] %>
              <% renglonesContCliDesAnt = m['renglonesContCliDes'] %>
              <% renglonesCreditoAnt = m['renglonesCredito'] %>
              <% articulosAnt = m['articulos'] %>
              <% articulosContGralAnt = m['articulosContGral'] %>
              <% articulosContCliDesAnt = m['articulosContCliDes'] %>
              <% articulosCreditoAnt = m['articulosCredito'] %>
            <% end %>
          <% end %>

          <tr>
          <td bgcolor="CCCCCC" ><P align=Center>Venta Neta </td>
          <td><P align=Center><%= number_to_currency(vtaNetaAct, :locale => :mx, :precision => 2) %> </td>
          <td><P align=Center><%= number_to_currency(vtaNetaContGralAct, :locale => :mx, :precision => 2) %> </td>
          <td><P align=Center><%= number_to_currency(vtaNetaContCliDesAct, :locale => :mx, :precision => 2) %> </td>
          <td><P align=Center><%= number_to_currency(vtaNetaCreditoAct, :locale => :mx, :precision => 2) %> </td>
          <td> </td>
          <td><P align=Center><%= number_to_currency(vtaNetaAnt, :locale => :mx, :precision => 2) %> </td>
          <td><P align=Center><%= number_to_currency(vtaNetaContGralAnt, :locale => :mx, :precision => 2) %> </td>
          <td><P align=Center><%= number_to_currency(vtaNetaContCliDesAnt, :locale => :mx, :precision => 2) %> </td>
          <td><P align=Center><%= number_to_currency(vtaNetaCreditoAnt, :locale => :mx, :precision => 2) %> </td>
          </tr>
          <tr>
          <td bgcolor="CCCCCC" ><P align=Center>Costo </td>
          <td><P align=Center><%= number_to_currency(vtaCostoAct, :locale => :mx, :precision => 2) %> </td>
          <td><P align=Center><%= number_to_currency(vtaCostoContGralAct, :locale => :mx, :precision => 2) %> </td>
          <td><P align=Center><%= number_to_currency(vtaCostoContCliDesAct, :locale => :mx, :precision => 2) %> </td>
          <td><P align=Center><%= number_to_currency(vtaCostoCreditoAct, :locale => :mx, :precision => 2) %> </td>
          <td> </td>
          <td><P align=Center><%= number_to_currency(vtaCostoAnt, :locale => :mx, :precision => 2) %> </td>
          <td><P align=Center><%= number_to_currency(vtaCostoContGralAnt, :locale => :mx, :precision => 2) %> </td>
          <td><P align=Center><%= number_to_currency(vtaCostoContCliDesAnt, :locale => :mx, :precision => 2) %> </td>
          <td><P align=Center><%= number_to_currency(vtaCostoCreditoAnt, :locale => :mx, :precision => 2) %> </td>
          </tr>
          <tr>
          <td bgcolor="CCCCCC" ><P align=Center>Margen util. </td>
          <td><P align=Center><%= number_to_percentage(mUtilAct, :locale => :mx, :precision => 2) %> </td>
          <td><P align=Center><%= number_to_percentage(mUtilContGralAct, :locale => :mx, :precision => 2) %> </td>
          <td><P align=Center><%= number_to_percentage(mUtilContCliDesAct, :locale => :mx, :precision => 2) %> </td>
          <td><P align=Center><%= number_to_percentage(mUtilCreditoAct, :locale => :mx, :precision => 2) %> </td>
          <td> </td>
          <td><P align=Center><%= number_to_percentage(mUtilAnt, :locale => :mx, :precision => 2) %> </td>
          <td><P align=Center><%= number_to_percentage(mUtilContGralAnt, :locale => :mx, :precision => 2) %> </td>
          <td><P align=Center><%= number_to_percentage(mUtilContCliDesAnt, :locale => :mx, :precision => 2) %> </td>
          <td><P align=Center><%= number_to_percentage(mUtilCreditoAnt, :locale => :mx, :precision => 2) %> </td>
          </tr>
          <tr>
          <td> </td>
          <td> </td>
          <td> </td>
          <td> </td>
          <td> </td>
          <td> </td>
          <td> </td>
          <td> </td>
          <td> </td>
          <td> </td>
          </tr>
          <tr>
          <td bgcolor="CCCCCC" ><P align=Center>Tickets </td>
          <td><P align=Center><%= number_with_delimiter(ticketsAct, :locale => :mx, :precision => 2) %> </td>
          <td><P align=Center><%= number_with_delimiter(ticketsContGralAct, :locale => :mx, :precision => 2) %> </td>
          <td><P align=Center><%= number_with_delimiter(ticketsContCliDesAct, :locale => :mx, :precision => 2) %> </td>
          <td><P align=Center><%= number_with_delimiter(ticketsCreditoAct, :locale => :mx, :precision => 2) %> </td>
          <td> </td>
          <td><P align=Center><%= number_with_delimiter(ticketsAnt, :locale => :mx, :precision => 2) %> </td>
          <td><P align=Center><%= number_with_delimiter(ticketsContGralAnt, :locale => :mx, :precision => 2) %> </td>
          <td><P align=Center><%= number_with_delimiter(ticketsContCliDesAnt, :locale => :mx, :precision => 2) %> </td>
          <td><P align=Center><%= number_with_delimiter(ticketsCreditoAnt, :locale => :mx, :precision => 2) %> </td>
          </tr>
          <tr>
          <td> </td>
          <td> </td>
          <td> </td>
          <td> </td>
          <td> </td>
          <td> </td>
          <td> </td>
          <td> </td>
          <td> </td>
          <td> </td>
          </tr>
          <tr>
          <td bgcolor="CCCCCC" ><P align=Center>Renglones </td>
          <td><P align=Center><%= number_with_delimiter(renglonesAct, :locale => :mx, :precision => 2) %> </td>
          <td><P align=Center><%= number_with_delimiter(renglonesContGralAct, :locale => :mx, :precision => 2) %> </td>
          <td><P align=Center><%= number_with_delimiter(renglonesContCliDesAct, :locale => :mx, :precision => 2) %> </td>
          <td><P align=Center><%= number_with_delimiter(renglonesCreditoAct, :locale => :mx, :precision => 2) %> </td>
          <td> </td>
          <td><P align=Center><%= number_with_delimiter(renglonesAnt, :locale => :mx, :precision => 2) %> </td>
          <td><P align=Center><%= number_with_delimiter(renglonesContGralAnt, :locale => :mx, :precision => 2) %> </td>
          <td><P align=Center><%= number_with_delimiter(renglonesContCliDesAnt, :locale => :mx, :precision => 2) %> </td>
          <td><P align=Center><%= number_with_delimiter(renglonesCreditoAnt, :locale => :mx, :precision => 2) %> </td>
          </tr>
          <tr>
          <td> </td>
          <td> </td>
          <td> </td>
          <td> </td>
          <td> </td>
          <td> </td>
          <td> </td>
          <td> </td>
          <td> </td>
          <td> </td>
          </tr>
          <tr>
          <td bgcolor="CCCCCC" ><P align=Center>Artículos </td>
          <td><P align=Center><%= number_with_delimiter(articulosAct, :locale => :mx, :precision => 2) %> </td>
          <td><P align=Center><%= number_with_delimiter(articulosContGralAct, :locale => :mx, :precision => 2) %> </td>
          <td><P align=Center><%= number_with_delimiter(articulosContCliDesAct, :locale => :mx, :precision => 2) %> </td>
          <td><P align=Center><%= number_with_delimiter(articulosCreditoAct, :locale => :mx, :precision => 2) %> </td>
          <td> </td>
          <td><P align=Center><%= number_with_delimiter(articulosAnt, :locale => :mx, :precision => 2) %> </td>
          <td><P align=Center><%= number_with_delimiter(articulosContGralAnt, :locale => :mx, :precision => 2) %> </td>
          <td><P align=Center><%= number_with_delimiter(articulosContCliDesAnt, :locale => :mx, :precision => 2) %> </td>
          <td><P align=Center><%= number_with_delimiter(articulosCreditoAnt, :locale => :mx, :precision => 2) %> </td>
          </tr>
        </tbody>
      </table>

      <br>
      <%= link_to "Descargar para Excel", repobjetivos_det_suc_path(zona: @zona, suc: @suc, periodo: @anomesactual, format: "csv") %>

      <script type="text/javascript" language="javascript" src="/jquery.dataTables.min.js"></script>
      <script type="text/javascript" language="javascript" src="/dataTables.bootstrap.js"></script>
      <%= javascript_include_tag "/dt_v3" %>

    <% else %>
      <br>
      Sin Datos.
    <% end %>
  <% end %>

</div>
</center>